// Code generated by mockery v2.53.0. DO NOT EDIT.

package etcd

import (
	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// MockExcludeOption is an autogenerated mock type for the ExcludeOption type
type MockExcludeOption struct {
	mock.Mock
}

type MockExcludeOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExcludeOption) EXPECT() *MockExcludeOption_Expecter {
	return &MockExcludeOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: cfg
func (_m *MockExcludeOption) Execute(cfg core.ConfigurationField) bool {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(core.ConfigurationField) bool); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockExcludeOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExcludeOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - cfg core.ConfigurationField
func (_e *MockExcludeOption_Expecter) Execute(cfg interface{}) *MockExcludeOption_Execute_Call {
	return &MockExcludeOption_Execute_Call{Call: _e.mock.On("Execute", cfg)}
}

func (_c *MockExcludeOption_Execute_Call) Run(run func(cfg core.ConfigurationField)) *MockExcludeOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(core.ConfigurationField))
	})
	return _c
}

func (_c *MockExcludeOption_Execute_Call) Return(_a0 bool) *MockExcludeOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExcludeOption_Execute_Call) RunAndReturn(run func(core.ConfigurationField) bool) *MockExcludeOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExcludeOption creates a new instance of MockExcludeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExcludeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExcludeOption {
	mock := &MockExcludeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
