// Code generated by mockery v2.53.0. DO NOT EDIT.

package etcd

import (
	core "github.com/cloudogu/ces-exporter/core"
	mock "github.com/stretchr/testify/mock"
)

// mockFilterOption is an autogenerated mock type for the filterOption type
type mockFilterOption struct {
	mock.Mock
}

type mockFilterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFilterOption) EXPECT() *mockFilterOption_Expecter {
	return &mockFilterOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: kvs
func (_m *mockFilterOption) Execute(kvs []core.KeyValue) []core.KeyValue {
	ret := _m.Called(kvs)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []core.KeyValue
	if rf, ok := ret.Get(0).(func([]core.KeyValue) []core.KeyValue); ok {
		r0 = rf(kvs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.KeyValue)
		}
	}

	return r0
}

// mockFilterOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockFilterOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - kvs []core.KeyValue
func (_e *mockFilterOption_Expecter) Execute(kvs interface{}) *mockFilterOption_Execute_Call {
	return &mockFilterOption_Execute_Call{Call: _e.mock.On("Execute", kvs)}
}

func (_c *mockFilterOption_Execute_Call) Run(run func(kvs []core.KeyValue)) *mockFilterOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]core.KeyValue))
	})
	return _c
}

func (_c *mockFilterOption_Execute_Call) Return(_a0 []core.KeyValue) *mockFilterOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFilterOption_Execute_Call) RunAndReturn(run func([]core.KeyValue) []core.KeyValue) *mockFilterOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFilterOption creates a new instance of mockFilterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFilterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFilterOption {
	mock := &mockFilterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
