// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Decrypter is an autogenerated mock type for the decrypter type
type Decrypter struct {
	mock.Mock
}

type Decrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *Decrypter) EXPECT() *Decrypter_Expecter {
	return &Decrypter_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: input
func (_m *Decrypter) Decrypt(input string) (string, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Decrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type Decrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - input string
func (_e *Decrypter_Expecter) Decrypt(input interface{}) *Decrypter_Decrypt_Call {
	return &Decrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", input)}
}

func (_c *Decrypter_Decrypt_Call) Run(run func(input string)) *Decrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Decrypter_Decrypt_Call) Return(_a0 string, _a1 error) *Decrypter_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Decrypter_Decrypt_Call) RunAndReturn(run func(string) (string, error)) *Decrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewDecrypter creates a new instance of Decrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Decrypter {
	mock := &Decrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
