// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	core "github.com/cloudogu/ces-exporter/core"

	mock "github.com/stretchr/testify/mock"
)

// GetKeyValuesClientFuncType is an autogenerated mock type for the getKeyValuesClientFuncType type
type GetKeyValuesClientFuncType struct {
	mock.Mock
}

type GetKeyValuesClientFuncType_Expecter struct {
	mock *mock.Mock
}

func (_m *GetKeyValuesClientFuncType) EXPECT() *GetKeyValuesClientFuncType_Expecter {
	return &GetKeyValuesClientFuncType_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: path, filters
func (_m *GetKeyValuesClientFuncType) Execute(path string, filters ...core.FilterOption) ([]core.KeyValue, error) {
	_va := make([]interface{}, len(filters))
	for _i := range filters {
		_va[_i] = filters[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []core.KeyValue
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...core.FilterOption) ([]core.KeyValue, error)); ok {
		return rf(path, filters...)
	}
	if rf, ok := ret.Get(0).(func(string, ...core.FilterOption) []core.KeyValue); ok {
		r0 = rf(path, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.KeyValue)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...core.FilterOption) error); ok {
		r1 = rf(path, filters...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKeyValuesClientFuncType_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetKeyValuesClientFuncType_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - path string
//   - filters ...core.FilterOption
func (_e *GetKeyValuesClientFuncType_Expecter) Execute(path interface{}, filters ...interface{}) *GetKeyValuesClientFuncType_Execute_Call {
	return &GetKeyValuesClientFuncType_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{path}, filters...)...)}
}

func (_c *GetKeyValuesClientFuncType_Execute_Call) Run(run func(path string, filters ...core.FilterOption)) *GetKeyValuesClientFuncType_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]core.FilterOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(core.FilterOption)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GetKeyValuesClientFuncType_Execute_Call) Return(_a0 []core.KeyValue, _a1 error) *GetKeyValuesClientFuncType_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetKeyValuesClientFuncType_Execute_Call) RunAndReturn(run func(string, ...core.FilterOption) ([]core.KeyValue, error)) *GetKeyValuesClientFuncType_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetKeyValuesClientFuncType creates a new instance of GetKeyValuesClientFuncType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetKeyValuesClientFuncType(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetKeyValuesClientFuncType {
	mock := &GetKeyValuesClientFuncType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
