// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v2 "github.com/cloudogu/k8s-dogu-operator/v3/api/v2"
)

// MockDoguClientInterface is an autogenerated mock type for the DoguClientInterface type
type MockDoguClientInterface struct {
	mock.Mock
}

type MockDoguClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguClientInterface) EXPECT() *MockDoguClientInterface_Expecter {
	return &MockDoguClientInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *MockDoguClientInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.Dogu, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v2.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*v2.Dogu, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v2.Dogu); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguClientInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDoguClientInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *MockDoguClientInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *MockDoguClientInterface_Get_Call {
	return &MockDoguClientInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *MockDoguClientInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *MockDoguClientInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *MockDoguClientInterface_Get_Call) Return(_a0 *v2.Dogu, _a1 error) *MockDoguClientInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguClientInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*v2.Dogu, error)) *MockDoguClientInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockDoguClientInterface) List(ctx context.Context, opts v1.ListOptions) (*v2.DoguList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v2.DoguList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*v2.DoguList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v2.DoguList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.DoguList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguClientInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDoguClientInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *MockDoguClientInterface_Expecter) List(ctx interface{}, opts interface{}) *MockDoguClientInterface_List_Call {
	return &MockDoguClientInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockDoguClientInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *MockDoguClientInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *MockDoguClientInterface_List_Call) Return(_a0 *v2.DoguList, _a1 error) *MockDoguClientInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguClientInterface_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*v2.DoguList, error)) *MockDoguClientInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, dogu, opts
func (_m *MockDoguClientInterface) Update(ctx context.Context, dogu *v2.Dogu, opts v1.UpdateOptions) (*v2.Dogu, error) {
	ret := _m.Called(ctx, dogu, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v2.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, v1.UpdateOptions) (*v2.Dogu, error)); ok {
		return rf(ctx, dogu, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, v1.UpdateOptions) *v2.Dogu); ok {
		r0 = rf(ctx, dogu, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, dogu, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguClientInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDoguClientInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *v2.Dogu
//   - opts v1.UpdateOptions
func (_e *MockDoguClientInterface_Expecter) Update(ctx interface{}, dogu interface{}, opts interface{}) *MockDoguClientInterface_Update_Call {
	return &MockDoguClientInterface_Update_Call{Call: _e.mock.On("Update", ctx, dogu, opts)}
}

func (_c *MockDoguClientInterface_Update_Call) Run(run func(ctx context.Context, dogu *v2.Dogu, opts v1.UpdateOptions)) *MockDoguClientInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *MockDoguClientInterface_Update_Call) Return(_a0 *v2.Dogu, _a1 error) *MockDoguClientInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguClientInterface_Update_Call) RunAndReturn(run func(context.Context, *v2.Dogu, v1.UpdateOptions) (*v2.Dogu, error)) *MockDoguClientInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguClientInterface creates a new instance of MockDoguClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguClientInterface {
	mock := &MockDoguClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
