// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// MockServiceClientInterface is an autogenerated mock type for the ServiceClientInterface type
type MockServiceClientInterface struct {
	mock.Mock
}

type MockServiceClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceClientInterface) EXPECT() *MockServiceClientInterface_Expecter {
	return &MockServiceClientInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name
func (_m *MockServiceClientInterface) Get(ctx context.Context, name string) (*v1.Service, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1.Service, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.Service); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceClientInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServiceClientInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServiceClientInterface_Expecter) Get(ctx interface{}, name interface{}) *MockServiceClientInterface_Get_Call {
	return &MockServiceClientInterface_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockServiceClientInterface_Get_Call) Run(run func(ctx context.Context, name string)) *MockServiceClientInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServiceClientInterface_Get_Call) Return(_a0 *v1.Service, _a1 error) *MockServiceClientInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceClientInterface_Get_Call) RunAndReturn(run func(context.Context, string) (*v1.Service, error)) *MockServiceClientInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, service
func (_m *MockServiceClientInterface) Update(ctx context.Context, service *v1.Service) (*v1.Service, error) {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Service) (*v1.Service, error)); ok {
		return rf(ctx, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Service) *v1.Service); ok {
		r0 = rf(ctx, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Service) error); ok {
		r1 = rf(ctx, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceClientInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceClientInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v1.Service
func (_e *MockServiceClientInterface_Expecter) Update(ctx interface{}, service interface{}) *MockServiceClientInterface_Update_Call {
	return &MockServiceClientInterface_Update_Call{Call: _e.mock.On("Update", ctx, service)}
}

func (_c *MockServiceClientInterface_Update_Call) Run(run func(ctx context.Context, service *v1.Service)) *MockServiceClientInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Service))
	})
	return _c
}

func (_c *MockServiceClientInterface_Update_Call) Return(_a0 *v1.Service, _a1 error) *MockServiceClientInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceClientInterface_Update_Call) RunAndReturn(run func(context.Context, *v1.Service) (*v1.Service, error)) *MockServiceClientInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceClientInterface creates a new instance of MockServiceClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceClientInterface {
	mock := &MockServiceClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
