// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import mock "github.com/stretchr/testify/mock"

// MockCronJobFunction is an autogenerated mock type for the CronJobFunction type
type MockCronJobFunction struct {
	mock.Mock
}

type MockCronJobFunction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronJobFunction) EXPECT() *MockCronJobFunction_Expecter {
	return &MockCronJobFunction_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockCronJobFunction) Execute() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCronJobFunction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCronJobFunction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockCronJobFunction_Expecter) Execute() *MockCronJobFunction_Execute_Call {
	return &MockCronJobFunction_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockCronJobFunction_Execute_Call) Run(run func()) *MockCronJobFunction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJobFunction_Execute_Call) Return(_a0 int, _a1 error) *MockCronJobFunction_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCronJobFunction_Execute_Call) RunAndReturn(run func() (int, error)) *MockCronJobFunction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCronJobFunction creates a new instance of MockCronJobFunction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronJobFunction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronJobFunction {
	mock := &MockCronJobFunction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
