// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockServiceClient is an autogenerated mock type for the serviceClient type
type mockServiceClient struct {
	mock.Mock
}

type mockServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceClient) EXPECT() *mockServiceClient_Expecter {
	return &mockServiceClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockServiceClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1.Service, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *corev1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*corev1.Service, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *corev1.Service); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockServiceClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockServiceClient_Get_Call {
	return &mockServiceClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockServiceClient_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockServiceClient_Get_Call) Return(_a0 *corev1.Service, _a1 error) *mockServiceClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceClient_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*corev1.Service, error)) *mockServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, service, opts
func (_m *mockServiceClient) Update(ctx context.Context, service *corev1.Service, opts v1.UpdateOptions) (*corev1.Service, error) {
	ret := _m.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *corev1.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Service, v1.UpdateOptions) (*corev1.Service, error)); ok {
		return rf(ctx, service, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.Service, v1.UpdateOptions) *corev1.Service); ok {
		r0 = rf(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.Service, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - service *corev1.Service
//   - opts v1.UpdateOptions
func (_e *mockServiceClient_Expecter) Update(ctx interface{}, service interface{}, opts interface{}) *mockServiceClient_Update_Call {
	return &mockServiceClient_Update_Call{Call: _e.mock.On("Update", ctx, service, opts)}
}

func (_c *mockServiceClient_Update_Call) Run(run func(ctx context.Context, service *corev1.Service, opts v1.UpdateOptions)) *mockServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.Service), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *mockServiceClient_Update_Call) Return(_a0 *corev1.Service, _a1 error) *mockServiceClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceClient_Update_Call) RunAndReturn(run func(context.Context, *corev1.Service, v1.UpdateOptions) (*corev1.Service, error)) *mockServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceClient creates a new instance of mockServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceClient {
	mock := &mockServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
