// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetExportDogu provides a mock function with given fields: ctx
func (_m *MockProvider) GetExportDogu(ctx context.Context) (*DoguExport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportDogu")
	}

	var r0 *DoguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*DoguExport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *DoguExport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DoguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportDogu'
type MockProvider_GetExportDogu_Call struct {
	*mock.Call
}

// GetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetExportDogu(ctx interface{}) *MockProvider_GetExportDogu_Call {
	return &MockProvider_GetExportDogu_Call{Call: _e.mock.On("GetExportDogu", ctx)}
}

func (_c *MockProvider_GetExportDogu_Call) Run(run func(ctx context.Context)) *MockProvider_GetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_GetExportDogu_Call) Return(_a0 *DoguExport, _a1 error) *MockProvider_GetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetExportDogu_Call) RunAndReturn(run func(context.Context) (*DoguExport, error)) *MockProvider_GetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportMode provides a mock function with given fields: ctx
func (_m *MockProvider) GetExportMode(ctx context.Context) (*ExportModeStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportMode")
	}

	var r0 *ExportModeStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ExportModeStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ExportModeStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExportModeStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetExportMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportMode'
type MockProvider_GetExportMode_Call struct {
	*mock.Call
}

// GetExportMode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetExportMode(ctx interface{}) *MockProvider_GetExportMode_Call {
	return &MockProvider_GetExportMode_Call{Call: _e.mock.On("GetExportMode", ctx)}
}

func (_c *MockProvider_GetExportMode_Call) Run(run func(ctx context.Context)) *MockProvider_GetExportMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_GetExportMode_Call) Return(_a0 *ExportModeStatus, _a1 error) *MockProvider_GetExportMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetExportMode_Call) RunAndReturn(run func(context.Context) (*ExportModeStatus, error)) *MockProvider_GetExportMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetExportDogu provides a mock function with given fields: doguName, ctx
func (_m *MockProvider) SetExportDogu(doguName string, ctx context.Context) (*DoguExport, error) {
	ret := _m.Called(doguName, ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetExportDogu")
	}

	var r0 *DoguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (*DoguExport, error)); ok {
		return rf(doguName, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) *DoguExport); ok {
		r0 = rf(doguName, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DoguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(doguName, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_SetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExportDogu'
type MockProvider_SetExportDogu_Call struct {
	*mock.Call
}

// SetExportDogu is a helper method to define mock.On call
//   - doguName string
//   - ctx context.Context
func (_e *MockProvider_Expecter) SetExportDogu(doguName interface{}, ctx interface{}) *MockProvider_SetExportDogu_Call {
	return &MockProvider_SetExportDogu_Call{Call: _e.mock.On("SetExportDogu", doguName, ctx)}
}

func (_c *MockProvider_SetExportDogu_Call) Run(run func(doguName string, ctx context.Context)) *MockProvider_SetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(context.Context))
	})
	return _c
}

func (_c *MockProvider_SetExportDogu_Call) Return(_a0 *DoguExport, _a1 error) *MockProvider_SetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_SetExportDogu_Call) RunAndReturn(run func(string, context.Context) (*DoguExport, error)) *MockProvider_SetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
