// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import mock "github.com/stretchr/testify/mock"

// mockSshBannerReader is an autogenerated mock type for the sshBannerReader type
type mockSshBannerReader struct {
	mock.Mock
}

type mockSshBannerReader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSshBannerReader) EXPECT() *mockSshBannerReader_Expecter {
	return &mockSshBannerReader_Expecter{mock: &_m.Mock}
}

// readSSHBanner provides a mock function with given fields: address
func (_m *mockSshBannerReader) readSSHBanner(address string) (string, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for readSSHBanner")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSshBannerReader_readSSHBanner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'readSSHBanner'
type mockSshBannerReader_readSSHBanner_Call struct {
	*mock.Call
}

// readSSHBanner is a helper method to define mock.On call
//   - address string
func (_e *mockSshBannerReader_Expecter) readSSHBanner(address interface{}) *mockSshBannerReader_readSSHBanner_Call {
	return &mockSshBannerReader_readSSHBanner_Call{Call: _e.mock.On("readSSHBanner", address)}
}

func (_c *mockSshBannerReader_readSSHBanner_Call) Run(run func(address string)) *mockSshBannerReader_readSSHBanner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockSshBannerReader_readSSHBanner_Call) Return(_a0 string, _a1 error) *mockSshBannerReader_readSSHBanner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSshBannerReader_readSSHBanner_Call) RunAndReturn(run func(string) (string, error)) *mockSshBannerReader_readSSHBanner_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSshBannerReader creates a new instance of mockSshBannerReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSshBannerReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSshBannerReader {
	mock := &mockSshBannerReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
