// Code generated by mockery v2.53.3. DO NOT EDIT.

package export

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetExportDogu provides a mock function with given fields: ctx
func (_m *MockProvider) GetExportDogu(ctx context.Context) (*doguExport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportDogu")
	}

	var r0 *doguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*doguExport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *doguExport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*doguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportDogu'
type MockProvider_GetExportDogu_Call struct {
	*mock.Call
}

// GetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetExportDogu(ctx interface{}) *MockProvider_GetExportDogu_Call {
	return &MockProvider_GetExportDogu_Call{Call: _e.mock.On("GetExportDogu", ctx)}
}

func (_c *MockProvider_GetExportDogu_Call) Run(run func(ctx context.Context)) *MockProvider_GetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_GetExportDogu_Call) Return(_a0 *doguExport, _a1 error) *MockProvider_GetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetExportDogu_Call) RunAndReturn(run func(context.Context) (*doguExport, error)) *MockProvider_GetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportMode provides a mock function with given fields: ctx
func (_m *MockProvider) GetExportMode(ctx context.Context) (*exportModeStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportMode")
	}

	var r0 *exportModeStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*exportModeStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *exportModeStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exportModeStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetExportMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportMode'
type MockProvider_GetExportMode_Call struct {
	*mock.Call
}

// GetExportMode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetExportMode(ctx interface{}) *MockProvider_GetExportMode_Call {
	return &MockProvider_GetExportMode_Call{Call: _e.mock.On("GetExportMode", ctx)}
}

func (_c *MockProvider_GetExportMode_Call) Run(run func(ctx context.Context)) *MockProvider_GetExportMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_GetExportMode_Call) Return(_a0 *exportModeStatus, _a1 error) *MockProvider_GetExportMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetExportMode_Call) RunAndReturn(run func(context.Context) (*exportModeStatus, error)) *MockProvider_GetExportMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetExportDogu provides a mock function with given fields: ctx, doguName
func (_m *MockProvider) SetExportDogu(ctx context.Context, doguName string) (*doguExport, error) {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for SetExportDogu")
	}

	var r0 *doguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*doguExport, error)); ok {
		return rf(ctx, doguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *doguExport); ok {
		r0 = rf(ctx, doguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*doguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_SetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExportDogu'
type MockProvider_SetExportDogu_Call struct {
	*mock.Call
}

// SetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *MockProvider_Expecter) SetExportDogu(ctx interface{}, doguName interface{}) *MockProvider_SetExportDogu_Call {
	return &MockProvider_SetExportDogu_Call{Call: _e.mock.On("SetExportDogu", ctx, doguName)}
}

func (_c *MockProvider_SetExportDogu_Call) Run(run func(ctx context.Context, doguName string)) *MockProvider_SetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvider_SetExportDogu_Call) Return(_a0 *doguExport, _a1 error) *MockProvider_SetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_SetExportDogu_Call) RunAndReturn(run func(context.Context, string) (*doguExport, error)) *MockProvider_SetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
