// Code generated by mockery v2.53.0. DO NOT EDIT.

package export

import (
	context "context"

	container "github.com/docker/docker/api/types/container"

	mock "github.com/stretchr/testify/mock"

	types "github.com/docker/docker/api/types"
)

// mockExecClient is an autogenerated mock type for the execClient type
type mockExecClient struct {
	mock.Mock
}

type mockExecClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExecClient) EXPECT() *mockExecClient_Expecter {
	return &mockExecClient_Expecter{mock: &_m.Mock}
}

// ContainerInspect provides a mock function with given fields: ctx, containerID
func (_m *mockExecClient) ContainerInspect(ctx context.Context, containerID string) (types.ContainerJSON, error) {
	ret := _m.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 types.ContainerJSON
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (types.ContainerJSON, error)); ok {
		return rf(ctx, containerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) types.ContainerJSON); ok {
		r0 = rf(ctx, containerID)
	} else {
		r0 = ret.Get(0).(types.ContainerJSON)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecClient_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type mockExecClient_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *mockExecClient_Expecter) ContainerInspect(ctx interface{}, containerID interface{}) *mockExecClient_ContainerInspect_Call {
	return &mockExecClient_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID)}
}

func (_c *mockExecClient_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string)) *mockExecClient_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockExecClient_ContainerInspect_Call) Return(_a0 types.ContainerJSON, _a1 error) *mockExecClient_ContainerInspect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecClient_ContainerInspect_Call) RunAndReturn(run func(context.Context, string) (types.ContainerJSON, error)) *mockExecClient_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function with given fields: ctx, options
func (_m *mockExecClient) ContainerList(ctx context.Context, options container.ListOptions) ([]types.Container, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 []types.Container
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, container.ListOptions) ([]types.Container, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, container.ListOptions) []types.Container); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Container)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, container.ListOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecClient_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type mockExecClient_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - options container.ListOptions
func (_e *mockExecClient_Expecter) ContainerList(ctx interface{}, options interface{}) *mockExecClient_ContainerList_Call {
	return &mockExecClient_ContainerList_Call{Call: _e.mock.On("ContainerList", ctx, options)}
}

func (_c *mockExecClient_ContainerList_Call) Run(run func(ctx context.Context, options container.ListOptions)) *mockExecClient_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(container.ListOptions))
	})
	return _c
}

func (_c *mockExecClient_ContainerList_Call) Return(_a0 []types.Container, _a1 error) *mockExecClient_ContainerList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecClient_ContainerList_Call) RunAndReturn(run func(context.Context, container.ListOptions) ([]types.Container, error)) *mockExecClient_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDogus provides a mock function with no fields
func (_m *mockExecClient) GetAllDogus() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllDogus")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExecClient_GetAllDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDogus'
type mockExecClient_GetAllDogus_Call struct {
	*mock.Call
}

// GetAllDogus is a helper method to define mock.On call
func (_e *mockExecClient_Expecter) GetAllDogus() *mockExecClient_GetAllDogus_Call {
	return &mockExecClient_GetAllDogus_Call{Call: _e.mock.On("GetAllDogus")}
}

func (_c *mockExecClient_GetAllDogus_Call) Run(run func()) *mockExecClient_GetAllDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockExecClient_GetAllDogus_Call) Return(_a0 []string, _a1 error) *mockExecClient_GetAllDogus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExecClient_GetAllDogus_Call) RunAndReturn(run func() ([]string, error)) *mockExecClient_GetAllDogus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExecClient creates a new instance of mockExecClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExecClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExecClient {
	mock := &mockExecClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
