### GET Maintenance-Mode
GET {{host}}/ces-exporter/maintenance/mode
X-CES-EXPORTER-API-KEY: {{apiKey}}

### Set Maintenance-Mode
POST {{host}}/ces-exporter/maintenance/mode
Content-Type: application/json
X-CES-EXPORTER-API-KEY: {{apiKey}}

{
  "activate": true,
  "title": "Migration in progress",
  "message": "This CES is migrating to a new instance"
}