#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

installed_version=$(dpkg-query -W -f='${Version}' ces-exporter)
docker rm -f ces-exporter

echo "Starting ces-exporter..."
docker run -p 7022:22 -v /var/lib/ces:/data -v /etc/ces/node_master:/etc/ces/node_master --net cesnet1 --name ces-exporter --restart=always -d "ces-exporter:${installed_version}"
EXPORTER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ces-exporter)
# Create service in etcd registry to make the nginx route the api endpoints
etcdctl set services/exporter/registrator:exporter:8025 "{\"name\":\"ces-exporter\",\"service\":\"${EXPORTER_IP}:8080\",\"port\":\"8080\",\"tags\":[\"webapp\"],\"healthStatus\":\"healthy\",\"attributes\":{}}"
docker restart nginx || true

if docker ps --filter "name=ces-exporter" --filter "status=running" | grep ces-exporter > /dev/null; then
  docker logs -f ces-exporter
else
  echo "failed to start ces-exporter"
  exit 1
fi
