// Code generated by mockery v2.53.0. DO NOT EDIT.

package main

import (
	ecosystem "github.com/cloudogu/k8s-component-operator/pkg/api/ecosystem"
	mock "github.com/stretchr/testify/mock"
)

// mockV1AlphaClientInterface is an autogenerated mock type for the v1AlphaClientInterface type
type mockV1AlphaClientInterface struct {
	mock.Mock
}

type mockV1AlphaClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockV1AlphaClientInterface) EXPECT() *mockV1AlphaClientInterface_Expecter {
	return &mockV1AlphaClientInterface_Expecter{mock: &_m.Mock}
}

// Components provides a mock function with given fields: namespace
func (_m *mockV1AlphaClientInterface) Components(namespace string) ecosystem.ComponentInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Components")
	}

	var r0 ecosystem.ComponentInterface
	if rf, ok := ret.Get(0).(func(string) ecosystem.ComponentInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecosystem.ComponentInterface)
		}
	}

	return r0
}

// mockV1AlphaClientInterface_Components_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Components'
type mockV1AlphaClientInterface_Components_Call struct {
	*mock.Call
}

// Components is a helper method to define mock.On call
//   - namespace string
func (_e *mockV1AlphaClientInterface_Expecter) Components(namespace interface{}) *mockV1AlphaClientInterface_Components_Call {
	return &mockV1AlphaClientInterface_Components_Call{Call: _e.mock.On("Components", namespace)}
}

func (_c *mockV1AlphaClientInterface_Components_Call) Run(run func(namespace string)) *mockV1AlphaClientInterface_Components_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockV1AlphaClientInterface_Components_Call) Return(_a0 ecosystem.ComponentInterface) *mockV1AlphaClientInterface_Components_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockV1AlphaClientInterface_Components_Call) RunAndReturn(run func(string) ecosystem.ComponentInterface) *mockV1AlphaClientInterface_Components_Call {
	_c.Call.Return(run)
	return _c
}

// newMockV1AlphaClientInterface creates a new instance of mockV1AlphaClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockV1AlphaClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockV1AlphaClientInterface {
	mock := &mockV1AlphaClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
