// Code generated by mockery v2.53.0. DO NOT EDIT.

package main

import (
	client "github.com/cloudogu/k8s-dogu-lib/v2/client"
	mock "github.com/stretchr/testify/mock"
)

// mockEcosystemDogusClient is an autogenerated mock type for the ecosystemDogusClient type
type mockEcosystemDogusClient struct {
	mock.Mock
}

type mockEcosystemDogusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEcosystemDogusClient) EXPECT() *mockEcosystemDogusClient_Expecter {
	return &mockEcosystemDogusClient_Expecter{mock: &_m.Mock}
}

// DoguRestarts provides a mock function with given fields: namespace
func (_m *mockEcosystemDogusClient) DoguRestarts(namespace string) client.DoguRestartInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DoguRestarts")
	}

	var r0 client.DoguRestartInterface
	if rf, ok := ret.Get(0).(func(string) client.DoguRestartInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.DoguRestartInterface)
		}
	}

	return r0
}

// mockEcosystemDogusClient_DoguRestarts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoguRestarts'
type mockEcosystemDogusClient_DoguRestarts_Call struct {
	*mock.Call
}

// DoguRestarts is a helper method to define mock.On call
//   - namespace string
func (_e *mockEcosystemDogusClient_Expecter) DoguRestarts(namespace interface{}) *mockEcosystemDogusClient_DoguRestarts_Call {
	return &mockEcosystemDogusClient_DoguRestarts_Call{Call: _e.mock.On("DoguRestarts", namespace)}
}

func (_c *mockEcosystemDogusClient_DoguRestarts_Call) Run(run func(namespace string)) *mockEcosystemDogusClient_DoguRestarts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockEcosystemDogusClient_DoguRestarts_Call) Return(_a0 client.DoguRestartInterface) *mockEcosystemDogusClient_DoguRestarts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEcosystemDogusClient_DoguRestarts_Call) RunAndReturn(run func(string) client.DoguRestartInterface) *mockEcosystemDogusClient_DoguRestarts_Call {
	_c.Call.Return(run)
	return _c
}

// Dogus provides a mock function with given fields: namespace
func (_m *mockEcosystemDogusClient) Dogus(namespace string) client.DoguInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Dogus")
	}

	var r0 client.DoguInterface
	if rf, ok := ret.Get(0).(func(string) client.DoguInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.DoguInterface)
		}
	}

	return r0
}

// mockEcosystemDogusClient_Dogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dogus'
type mockEcosystemDogusClient_Dogus_Call struct {
	*mock.Call
}

// Dogus is a helper method to define mock.On call
//   - namespace string
func (_e *mockEcosystemDogusClient_Expecter) Dogus(namespace interface{}) *mockEcosystemDogusClient_Dogus_Call {
	return &mockEcosystemDogusClient_Dogus_Call{Call: _e.mock.On("Dogus", namespace)}
}

func (_c *mockEcosystemDogusClient_Dogus_Call) Run(run func(namespace string)) *mockEcosystemDogusClient_Dogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockEcosystemDogusClient_Dogus_Call) Return(_a0 client.DoguInterface) *mockEcosystemDogusClient_Dogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEcosystemDogusClient_Dogus_Call) RunAndReturn(run func(string) client.DoguInterface) *mockEcosystemDogusClient_Dogus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEcosystemDogusClient creates a new instance of mockEcosystemDogusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEcosystemDogusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEcosystemDogusClient {
	mock := &mockEcosystemDogusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
