// Code generated by mockery v2.53.0. DO NOT EDIT.

package main

import (
	context "context"

	configuration "github.com/cloudogu/ces-exporter/configuration"
	export "github.com/cloudogu/ces-exporter/export"
	maintenance "github.com/cloudogu/ces-exporter/maintenance"
	systeminfo "github.com/cloudogu/ces-exporter/systeminfo"
	mock "github.com/stretchr/testify/mock"
)

// mockControllerProvider is an autogenerated mock type for the controllerProvider type
type mockControllerProvider struct {
	mock.Mock
}

type mockControllerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockControllerProvider) EXPECT() *mockControllerProvider_Expecter {
	return &mockControllerProvider_Expecter{mock: &_m.Mock}
}

// createControllers provides a mock function with given fields: ctx
func (_m *mockControllerProvider) createControllers(ctx context.Context) (*systeminfo.Controller, *configuration.Controller, *maintenance.Controller, *export.Controller) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for createControllers")
	}

	var r0 *systeminfo.Controller
	var r1 *configuration.Controller
	var r2 *maintenance.Controller
	var r3 *export.Controller
	if rf, ok := ret.Get(0).(func(context.Context) (*systeminfo.Controller, *configuration.Controller, *maintenance.Controller, *export.Controller)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *systeminfo.Controller); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systeminfo.Controller)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *configuration.Controller); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*configuration.Controller)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) *maintenance.Controller); ok {
		r2 = rf(ctx)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*maintenance.Controller)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context) *export.Controller); ok {
		r3 = rf(ctx)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*export.Controller)
		}
	}

	return r0, r1, r2, r3
}

// mockControllerProvider_createControllers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createControllers'
type mockControllerProvider_createControllers_Call struct {
	*mock.Call
}

// createControllers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockControllerProvider_Expecter) createControllers(ctx interface{}) *mockControllerProvider_createControllers_Call {
	return &mockControllerProvider_createControllers_Call{Call: _e.mock.On("createControllers", ctx)}
}

func (_c *mockControllerProvider_createControllers_Call) Run(run func(ctx context.Context)) *mockControllerProvider_createControllers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockControllerProvider_createControllers_Call) Return(_a0 *systeminfo.Controller, _a1 *configuration.Controller, _a2 *maintenance.Controller, _a3 *export.Controller) *mockControllerProvider_createControllers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *mockControllerProvider_createControllers_Call) RunAndReturn(run func(context.Context) (*systeminfo.Controller, *configuration.Controller, *maintenance.Controller, *export.Controller)) *mockControllerProvider_createControllers_Call {
	_c.Call.Return(run)
	return _c
}

// newMockControllerProvider creates a new instance of mockControllerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockControllerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockControllerProvider {
	mock := &mockControllerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
