// Code generated by mockery v2.53.0. DO NOT EDIT.

package systeminfo

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1 "k8s.io/client-go/kubernetes/typed/core/v1"
)

// mockCorev1Client is an autogenerated mock type for the corev1Client type
type mockCorev1Client struct {
	mock.Mock
}

type mockCorev1Client_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCorev1Client) EXPECT() *mockCorev1Client_Expecter {
	return &mockCorev1Client_Expecter{mock: &_m.Mock}
}

// ComponentStatuses provides a mock function with no fields
func (_m *mockCorev1Client) ComponentStatuses() v1.ComponentStatusInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ComponentStatuses")
	}

	var r0 v1.ComponentStatusInterface
	if rf, ok := ret.Get(0).(func() v1.ComponentStatusInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ComponentStatusInterface)
		}
	}

	return r0
}

// mockCorev1Client_ComponentStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComponentStatuses'
type mockCorev1Client_ComponentStatuses_Call struct {
	*mock.Call
}

// ComponentStatuses is a helper method to define mock.On call
func (_e *mockCorev1Client_Expecter) ComponentStatuses() *mockCorev1Client_ComponentStatuses_Call {
	return &mockCorev1Client_ComponentStatuses_Call{Call: _e.mock.On("ComponentStatuses")}
}

func (_c *mockCorev1Client_ComponentStatuses_Call) Run(run func()) *mockCorev1Client_ComponentStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCorev1Client_ComponentStatuses_Call) Return(_a0 v1.ComponentStatusInterface) *mockCorev1Client_ComponentStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_ComponentStatuses_Call) RunAndReturn(run func() v1.ComponentStatusInterface) *mockCorev1Client_ComponentStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigMaps provides a mock function with given fields: namespace
func (_m *mockCorev1Client) ConfigMaps(namespace string) v1.ConfigMapInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ConfigMaps")
	}

	var r0 v1.ConfigMapInterface
	if rf, ok := ret.Get(0).(func(string) v1.ConfigMapInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ConfigMapInterface)
		}
	}

	return r0
}

// mockCorev1Client_ConfigMaps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigMaps'
type mockCorev1Client_ConfigMaps_Call struct {
	*mock.Call
}

// ConfigMaps is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) ConfigMaps(namespace interface{}) *mockCorev1Client_ConfigMaps_Call {
	return &mockCorev1Client_ConfigMaps_Call{Call: _e.mock.On("ConfigMaps", namespace)}
}

func (_c *mockCorev1Client_ConfigMaps_Call) Run(run func(namespace string)) *mockCorev1Client_ConfigMaps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_ConfigMaps_Call) Return(_a0 v1.ConfigMapInterface) *mockCorev1Client_ConfigMaps_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_ConfigMaps_Call) RunAndReturn(run func(string) v1.ConfigMapInterface) *mockCorev1Client_ConfigMaps_Call {
	_c.Call.Return(run)
	return _c
}

// Endpoints provides a mock function with given fields: namespace
func (_m *mockCorev1Client) Endpoints(namespace string) v1.EndpointsInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Endpoints")
	}

	var r0 v1.EndpointsInterface
	if rf, ok := ret.Get(0).(func(string) v1.EndpointsInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.EndpointsInterface)
		}
	}

	return r0
}

// mockCorev1Client_Endpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoints'
type mockCorev1Client_Endpoints_Call struct {
	*mock.Call
}

// Endpoints is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) Endpoints(namespace interface{}) *mockCorev1Client_Endpoints_Call {
	return &mockCorev1Client_Endpoints_Call{Call: _e.mock.On("Endpoints", namespace)}
}

func (_c *mockCorev1Client_Endpoints_Call) Run(run func(namespace string)) *mockCorev1Client_Endpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_Endpoints_Call) Return(_a0 v1.EndpointsInterface) *mockCorev1Client_Endpoints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Endpoints_Call) RunAndReturn(run func(string) v1.EndpointsInterface) *mockCorev1Client_Endpoints_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with given fields: namespace
func (_m *mockCorev1Client) Events(namespace string) v1.EventInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 v1.EventInterface
	if rf, ok := ret.Get(0).(func(string) v1.EventInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.EventInterface)
		}
	}

	return r0
}

// mockCorev1Client_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type mockCorev1Client_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) Events(namespace interface{}) *mockCorev1Client_Events_Call {
	return &mockCorev1Client_Events_Call{Call: _e.mock.On("Events", namespace)}
}

func (_c *mockCorev1Client_Events_Call) Run(run func(namespace string)) *mockCorev1Client_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_Events_Call) Return(_a0 v1.EventInterface) *mockCorev1Client_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Events_Call) RunAndReturn(run func(string) v1.EventInterface) *mockCorev1Client_Events_Call {
	_c.Call.Return(run)
	return _c
}

// LimitRanges provides a mock function with given fields: namespace
func (_m *mockCorev1Client) LimitRanges(namespace string) v1.LimitRangeInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for LimitRanges")
	}

	var r0 v1.LimitRangeInterface
	if rf, ok := ret.Get(0).(func(string) v1.LimitRangeInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.LimitRangeInterface)
		}
	}

	return r0
}

// mockCorev1Client_LimitRanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LimitRanges'
type mockCorev1Client_LimitRanges_Call struct {
	*mock.Call
}

// LimitRanges is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) LimitRanges(namespace interface{}) *mockCorev1Client_LimitRanges_Call {
	return &mockCorev1Client_LimitRanges_Call{Call: _e.mock.On("LimitRanges", namespace)}
}

func (_c *mockCorev1Client_LimitRanges_Call) Run(run func(namespace string)) *mockCorev1Client_LimitRanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_LimitRanges_Call) Return(_a0 v1.LimitRangeInterface) *mockCorev1Client_LimitRanges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_LimitRanges_Call) RunAndReturn(run func(string) v1.LimitRangeInterface) *mockCorev1Client_LimitRanges_Call {
	_c.Call.Return(run)
	return _c
}

// Namespaces provides a mock function with no fields
func (_m *mockCorev1Client) Namespaces() v1.NamespaceInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Namespaces")
	}

	var r0 v1.NamespaceInterface
	if rf, ok := ret.Get(0).(func() v1.NamespaceInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.NamespaceInterface)
		}
	}

	return r0
}

// mockCorev1Client_Namespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Namespaces'
type mockCorev1Client_Namespaces_Call struct {
	*mock.Call
}

// Namespaces is a helper method to define mock.On call
func (_e *mockCorev1Client_Expecter) Namespaces() *mockCorev1Client_Namespaces_Call {
	return &mockCorev1Client_Namespaces_Call{Call: _e.mock.On("Namespaces")}
}

func (_c *mockCorev1Client_Namespaces_Call) Run(run func()) *mockCorev1Client_Namespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCorev1Client_Namespaces_Call) Return(_a0 v1.NamespaceInterface) *mockCorev1Client_Namespaces_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Namespaces_Call) RunAndReturn(run func() v1.NamespaceInterface) *mockCorev1Client_Namespaces_Call {
	_c.Call.Return(run)
	return _c
}

// Nodes provides a mock function with no fields
func (_m *mockCorev1Client) Nodes() v1.NodeInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nodes")
	}

	var r0 v1.NodeInterface
	if rf, ok := ret.Get(0).(func() v1.NodeInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.NodeInterface)
		}
	}

	return r0
}

// mockCorev1Client_Nodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nodes'
type mockCorev1Client_Nodes_Call struct {
	*mock.Call
}

// Nodes is a helper method to define mock.On call
func (_e *mockCorev1Client_Expecter) Nodes() *mockCorev1Client_Nodes_Call {
	return &mockCorev1Client_Nodes_Call{Call: _e.mock.On("Nodes")}
}

func (_c *mockCorev1Client_Nodes_Call) Run(run func()) *mockCorev1Client_Nodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCorev1Client_Nodes_Call) Return(_a0 v1.NodeInterface) *mockCorev1Client_Nodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Nodes_Call) RunAndReturn(run func() v1.NodeInterface) *mockCorev1Client_Nodes_Call {
	_c.Call.Return(run)
	return _c
}

// PersistentVolumeClaims provides a mock function with given fields: namespace
func (_m *mockCorev1Client) PersistentVolumeClaims(namespace string) v1.PersistentVolumeClaimInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for PersistentVolumeClaims")
	}

	var r0 v1.PersistentVolumeClaimInterface
	if rf, ok := ret.Get(0).(func(string) v1.PersistentVolumeClaimInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.PersistentVolumeClaimInterface)
		}
	}

	return r0
}

// mockCorev1Client_PersistentVolumeClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistentVolumeClaims'
type mockCorev1Client_PersistentVolumeClaims_Call struct {
	*mock.Call
}

// PersistentVolumeClaims is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) PersistentVolumeClaims(namespace interface{}) *mockCorev1Client_PersistentVolumeClaims_Call {
	return &mockCorev1Client_PersistentVolumeClaims_Call{Call: _e.mock.On("PersistentVolumeClaims", namespace)}
}

func (_c *mockCorev1Client_PersistentVolumeClaims_Call) Run(run func(namespace string)) *mockCorev1Client_PersistentVolumeClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_PersistentVolumeClaims_Call) Return(_a0 v1.PersistentVolumeClaimInterface) *mockCorev1Client_PersistentVolumeClaims_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_PersistentVolumeClaims_Call) RunAndReturn(run func(string) v1.PersistentVolumeClaimInterface) *mockCorev1Client_PersistentVolumeClaims_Call {
	_c.Call.Return(run)
	return _c
}

// PersistentVolumes provides a mock function with no fields
func (_m *mockCorev1Client) PersistentVolumes() v1.PersistentVolumeInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PersistentVolumes")
	}

	var r0 v1.PersistentVolumeInterface
	if rf, ok := ret.Get(0).(func() v1.PersistentVolumeInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.PersistentVolumeInterface)
		}
	}

	return r0
}

// mockCorev1Client_PersistentVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistentVolumes'
type mockCorev1Client_PersistentVolumes_Call struct {
	*mock.Call
}

// PersistentVolumes is a helper method to define mock.On call
func (_e *mockCorev1Client_Expecter) PersistentVolumes() *mockCorev1Client_PersistentVolumes_Call {
	return &mockCorev1Client_PersistentVolumes_Call{Call: _e.mock.On("PersistentVolumes")}
}

func (_c *mockCorev1Client_PersistentVolumes_Call) Run(run func()) *mockCorev1Client_PersistentVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCorev1Client_PersistentVolumes_Call) Return(_a0 v1.PersistentVolumeInterface) *mockCorev1Client_PersistentVolumes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_PersistentVolumes_Call) RunAndReturn(run func() v1.PersistentVolumeInterface) *mockCorev1Client_PersistentVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// PodTemplates provides a mock function with given fields: namespace
func (_m *mockCorev1Client) PodTemplates(namespace string) v1.PodTemplateInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for PodTemplates")
	}

	var r0 v1.PodTemplateInterface
	if rf, ok := ret.Get(0).(func(string) v1.PodTemplateInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.PodTemplateInterface)
		}
	}

	return r0
}

// mockCorev1Client_PodTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PodTemplates'
type mockCorev1Client_PodTemplates_Call struct {
	*mock.Call
}

// PodTemplates is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) PodTemplates(namespace interface{}) *mockCorev1Client_PodTemplates_Call {
	return &mockCorev1Client_PodTemplates_Call{Call: _e.mock.On("PodTemplates", namespace)}
}

func (_c *mockCorev1Client_PodTemplates_Call) Run(run func(namespace string)) *mockCorev1Client_PodTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_PodTemplates_Call) Return(_a0 v1.PodTemplateInterface) *mockCorev1Client_PodTemplates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_PodTemplates_Call) RunAndReturn(run func(string) v1.PodTemplateInterface) *mockCorev1Client_PodTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// Pods provides a mock function with given fields: namespace
func (_m *mockCorev1Client) Pods(namespace string) v1.PodInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Pods")
	}

	var r0 v1.PodInterface
	if rf, ok := ret.Get(0).(func(string) v1.PodInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.PodInterface)
		}
	}

	return r0
}

// mockCorev1Client_Pods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pods'
type mockCorev1Client_Pods_Call struct {
	*mock.Call
}

// Pods is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) Pods(namespace interface{}) *mockCorev1Client_Pods_Call {
	return &mockCorev1Client_Pods_Call{Call: _e.mock.On("Pods", namespace)}
}

func (_c *mockCorev1Client_Pods_Call) Run(run func(namespace string)) *mockCorev1Client_Pods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_Pods_Call) Return(_a0 v1.PodInterface) *mockCorev1Client_Pods_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Pods_Call) RunAndReturn(run func(string) v1.PodInterface) *mockCorev1Client_Pods_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *mockCorev1Client) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// mockCorev1Client_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type mockCorev1Client_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *mockCorev1Client_Expecter) RESTClient() *mockCorev1Client_RESTClient_Call {
	return &mockCorev1Client_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *mockCorev1Client_RESTClient_Call) Run(run func()) *mockCorev1Client_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCorev1Client_RESTClient_Call) Return(_a0 rest.Interface) *mockCorev1Client_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_RESTClient_Call) RunAndReturn(run func() rest.Interface) *mockCorev1Client_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ReplicationControllers provides a mock function with given fields: namespace
func (_m *mockCorev1Client) ReplicationControllers(namespace string) v1.ReplicationControllerInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReplicationControllers")
	}

	var r0 v1.ReplicationControllerInterface
	if rf, ok := ret.Get(0).(func(string) v1.ReplicationControllerInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ReplicationControllerInterface)
		}
	}

	return r0
}

// mockCorev1Client_ReplicationControllers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplicationControllers'
type mockCorev1Client_ReplicationControllers_Call struct {
	*mock.Call
}

// ReplicationControllers is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) ReplicationControllers(namespace interface{}) *mockCorev1Client_ReplicationControllers_Call {
	return &mockCorev1Client_ReplicationControllers_Call{Call: _e.mock.On("ReplicationControllers", namespace)}
}

func (_c *mockCorev1Client_ReplicationControllers_Call) Run(run func(namespace string)) *mockCorev1Client_ReplicationControllers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_ReplicationControllers_Call) Return(_a0 v1.ReplicationControllerInterface) *mockCorev1Client_ReplicationControllers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_ReplicationControllers_Call) RunAndReturn(run func(string) v1.ReplicationControllerInterface) *mockCorev1Client_ReplicationControllers_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceQuotas provides a mock function with given fields: namespace
func (_m *mockCorev1Client) ResourceQuotas(namespace string) v1.ResourceQuotaInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ResourceQuotas")
	}

	var r0 v1.ResourceQuotaInterface
	if rf, ok := ret.Get(0).(func(string) v1.ResourceQuotaInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ResourceQuotaInterface)
		}
	}

	return r0
}

// mockCorev1Client_ResourceQuotas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceQuotas'
type mockCorev1Client_ResourceQuotas_Call struct {
	*mock.Call
}

// ResourceQuotas is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) ResourceQuotas(namespace interface{}) *mockCorev1Client_ResourceQuotas_Call {
	return &mockCorev1Client_ResourceQuotas_Call{Call: _e.mock.On("ResourceQuotas", namespace)}
}

func (_c *mockCorev1Client_ResourceQuotas_Call) Run(run func(namespace string)) *mockCorev1Client_ResourceQuotas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_ResourceQuotas_Call) Return(_a0 v1.ResourceQuotaInterface) *mockCorev1Client_ResourceQuotas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_ResourceQuotas_Call) RunAndReturn(run func(string) v1.ResourceQuotaInterface) *mockCorev1Client_ResourceQuotas_Call {
	_c.Call.Return(run)
	return _c
}

// Secrets provides a mock function with given fields: namespace
func (_m *mockCorev1Client) Secrets(namespace string) v1.SecretInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Secrets")
	}

	var r0 v1.SecretInterface
	if rf, ok := ret.Get(0).(func(string) v1.SecretInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.SecretInterface)
		}
	}

	return r0
}

// mockCorev1Client_Secrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secrets'
type mockCorev1Client_Secrets_Call struct {
	*mock.Call
}

// Secrets is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) Secrets(namespace interface{}) *mockCorev1Client_Secrets_Call {
	return &mockCorev1Client_Secrets_Call{Call: _e.mock.On("Secrets", namespace)}
}

func (_c *mockCorev1Client_Secrets_Call) Run(run func(namespace string)) *mockCorev1Client_Secrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_Secrets_Call) Return(_a0 v1.SecretInterface) *mockCorev1Client_Secrets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Secrets_Call) RunAndReturn(run func(string) v1.SecretInterface) *mockCorev1Client_Secrets_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceAccounts provides a mock function with given fields: namespace
func (_m *mockCorev1Client) ServiceAccounts(namespace string) v1.ServiceAccountInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ServiceAccounts")
	}

	var r0 v1.ServiceAccountInterface
	if rf, ok := ret.Get(0).(func(string) v1.ServiceAccountInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ServiceAccountInterface)
		}
	}

	return r0
}

// mockCorev1Client_ServiceAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceAccounts'
type mockCorev1Client_ServiceAccounts_Call struct {
	*mock.Call
}

// ServiceAccounts is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) ServiceAccounts(namespace interface{}) *mockCorev1Client_ServiceAccounts_Call {
	return &mockCorev1Client_ServiceAccounts_Call{Call: _e.mock.On("ServiceAccounts", namespace)}
}

func (_c *mockCorev1Client_ServiceAccounts_Call) Run(run func(namespace string)) *mockCorev1Client_ServiceAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_ServiceAccounts_Call) Return(_a0 v1.ServiceAccountInterface) *mockCorev1Client_ServiceAccounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_ServiceAccounts_Call) RunAndReturn(run func(string) v1.ServiceAccountInterface) *mockCorev1Client_ServiceAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function with given fields: namespace
func (_m *mockCorev1Client) Services(namespace string) v1.ServiceInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 v1.ServiceInterface
	if rf, ok := ret.Get(0).(func(string) v1.ServiceInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ServiceInterface)
		}
	}

	return r0
}

// mockCorev1Client_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type mockCorev1Client_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
//   - namespace string
func (_e *mockCorev1Client_Expecter) Services(namespace interface{}) *mockCorev1Client_Services_Call {
	return &mockCorev1Client_Services_Call{Call: _e.mock.On("Services", namespace)}
}

func (_c *mockCorev1Client_Services_Call) Run(run func(namespace string)) *mockCorev1Client_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCorev1Client_Services_Call) Return(_a0 v1.ServiceInterface) *mockCorev1Client_Services_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCorev1Client_Services_Call) RunAndReturn(run func(string) v1.ServiceInterface) *mockCorev1Client_Services_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCorev1Client creates a new instance of mockCorev1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCorev1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCorev1Client {
	mock := &mockCorev1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
