// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import mock "github.com/stretchr/testify/mock"

// mockVolumeSizeGetter is an autogenerated mock type for the volumeSizeGetter type
type mockVolumeSizeGetter struct {
	mock.Mock
}

type mockVolumeSizeGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockVolumeSizeGetter) EXPECT() *mockVolumeSizeGetter_Expecter {
	return &mockVolumeSizeGetter_Expecter{mock: &_m.Mock}
}

// GetVolumeSizeInBytes provides a mock function with given fields: dogu
func (_m *mockVolumeSizeGetter) GetVolumeSizeInBytes(dogu string) (int64, error) {
	ret := _m.Called(dogu)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeSizeInBytes")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(dogu)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dogu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockVolumeSizeGetter_GetVolumeSizeInBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeSizeInBytes'
type mockVolumeSizeGetter_GetVolumeSizeInBytes_Call struct {
	*mock.Call
}

// GetVolumeSizeInBytes is a helper method to define mock.On call
//   - dogu string
func (_e *mockVolumeSizeGetter_Expecter) GetVolumeSizeInBytes(dogu interface{}) *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call {
	return &mockVolumeSizeGetter_GetVolumeSizeInBytes_Call{Call: _e.mock.On("GetVolumeSizeInBytes", dogu)}
}

func (_c *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call) Run(run func(dogu string)) *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call) Return(_a0 int64, _a1 error) *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call) RunAndReturn(run func(string) (int64, error)) *mockVolumeSizeGetter_GetVolumeSizeInBytes_Call {
	_c.Call.Return(run)
	return _c
}

// newMockVolumeSizeGetter creates a new instance of mockVolumeSizeGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockVolumeSizeGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockVolumeSizeGetter {
	mock := &mockVolumeSizeGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
