// Code generated by mockery v2.53.0. DO NOT EDIT.

package systeminfo

import mock "github.com/stretchr/testify/mock"

// mockCommandExecutor is an autogenerated mock type for the commandExecutor type
type mockCommandExecutor struct {
	mock.Mock
}

type mockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCommandExecutor) EXPECT() *mockCommandExecutor_Expecter {
	return &mockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Output provides a mock function with no fields
func (_m *mockCommandExecutor) Output() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCommandExecutor_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type mockCommandExecutor_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
func (_e *mockCommandExecutor_Expecter) Output() *mockCommandExecutor_Output_Call {
	return &mockCommandExecutor_Output_Call{Call: _e.mock.On("Output")}
}

func (_c *mockCommandExecutor_Output_Call) Run(run func()) *mockCommandExecutor_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommandExecutor_Output_Call) Return(_a0 []byte, _a1 error) *mockCommandExecutor_Output_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCommandExecutor_Output_Call) RunAndReturn(run func() ([]byte, error)) *mockCommandExecutor_Output_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCommandExecutor creates a new instance of mockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCommandExecutor {
	mock := &mockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
