// Code generated by mockery v2.53.0. DO NOT EDIT.

package systeminfo

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemInfoProvider is an autogenerated mock type for the SystemInfoProvider type
type MockSystemInfoProvider struct {
	mock.Mock
}

type MockSystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemInfoProvider) EXPECT() *MockSystemInfoProvider_Expecter {
	return &MockSystemInfoProvider_Expecter{mock: &_m.Mock}
}

// getComponents provides a mock function with given fields: ctx
func (_m *MockSystemInfoProvider) getComponents(ctx context.Context) ([]component, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getComponents")
	}

	var r0 []component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]component, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []component); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemInfoProvider_getComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getComponents'
type MockSystemInfoProvider_getComponents_Call struct {
	*mock.Call
}

// getComponents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoProvider_Expecter) getComponents(ctx interface{}) *MockSystemInfoProvider_getComponents_Call {
	return &MockSystemInfoProvider_getComponents_Call{Call: _e.mock.On("getComponents", ctx)}
}

func (_c *MockSystemInfoProvider_getComponents_Call) Run(run func(ctx context.Context)) *MockSystemInfoProvider_getComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoProvider_getComponents_Call) Return(_a0 []component, _a1 error) *MockSystemInfoProvider_getComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemInfoProvider_getComponents_Call) RunAndReturn(run func(context.Context) ([]component, error)) *MockSystemInfoProvider_getComponents_Call {
	_c.Call.Return(run)
	return _c
}

// getDogus provides a mock function with given fields: ctx
func (_m *MockSystemInfoProvider) getDogus(ctx context.Context) ([]dogu, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getDogus")
	}

	var r0 []dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dogu, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dogu); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemInfoProvider_getDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDogus'
type MockSystemInfoProvider_getDogus_Call struct {
	*mock.Call
}

// getDogus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoProvider_Expecter) getDogus(ctx interface{}) *MockSystemInfoProvider_getDogus_Call {
	return &MockSystemInfoProvider_getDogus_Call{Call: _e.mock.On("getDogus", ctx)}
}

func (_c *MockSystemInfoProvider_getDogus_Call) Run(run func(ctx context.Context)) *MockSystemInfoProvider_getDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoProvider_getDogus_Call) Return(_a0 []dogu, _a1 error) *MockSystemInfoProvider_getDogus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemInfoProvider_getDogus_Call) RunAndReturn(run func(context.Context) ([]dogu, error)) *MockSystemInfoProvider_getDogus_Call {
	_c.Call.Return(run)
	return _c
}

// getFqdn provides a mock function with given fields: ctx
func (_m *MockSystemInfoProvider) getFqdn(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getFqdn")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemInfoProvider_getFqdn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getFqdn'
type MockSystemInfoProvider_getFqdn_Call struct {
	*mock.Call
}

// getFqdn is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoProvider_Expecter) getFqdn(ctx interface{}) *MockSystemInfoProvider_getFqdn_Call {
	return &MockSystemInfoProvider_getFqdn_Call{Call: _e.mock.On("getFqdn", ctx)}
}

func (_c *MockSystemInfoProvider_getFqdn_Call) Run(run func(ctx context.Context)) *MockSystemInfoProvider_getFqdn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoProvider_getFqdn_Call) Return(_a0 string, _a1 error) *MockSystemInfoProvider_getFqdn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemInfoProvider_getFqdn_Call) RunAndReturn(run func(context.Context) (string, error)) *MockSystemInfoProvider_getFqdn_Call {
	_c.Call.Return(run)
	return _c
}

// isMultinode provides a mock function with no fields
func (_m *MockSystemInfoProvider) isMultinode() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for isMultinode")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSystemInfoProvider_isMultinode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isMultinode'
type MockSystemInfoProvider_isMultinode_Call struct {
	*mock.Call
}

// isMultinode is a helper method to define mock.On call
func (_e *MockSystemInfoProvider_Expecter) isMultinode() *MockSystemInfoProvider_isMultinode_Call {
	return &MockSystemInfoProvider_isMultinode_Call{Call: _e.mock.On("isMultinode")}
}

func (_c *MockSystemInfoProvider_isMultinode_Call) Run(run func()) *MockSystemInfoProvider_isMultinode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemInfoProvider_isMultinode_Call) Return(_a0 bool) *MockSystemInfoProvider_isMultinode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemInfoProvider_isMultinode_Call) RunAndReturn(run func() bool) *MockSystemInfoProvider_isMultinode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemInfoProvider creates a new instance of MockSystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemInfoProvider {
	mock := &MockSystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
