// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguGetter is an autogenerated mock type for the doguGetter type
type mockDoguGetter struct {
	mock.Mock
}

type mockDoguGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguGetter) EXPECT() *mockDoguGetter_Expecter {
	return &mockDoguGetter_Expecter{mock: &_m.Mock}
}

// GetAllDogus provides a mock function with no fields
func (_m *mockDoguGetter) GetAllDogus() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllDogus")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguGetter_GetAllDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDogus'
type mockDoguGetter_GetAllDogus_Call struct {
	*mock.Call
}

// GetAllDogus is a helper method to define mock.On call
func (_e *mockDoguGetter_Expecter) GetAllDogus() *mockDoguGetter_GetAllDogus_Call {
	return &mockDoguGetter_GetAllDogus_Call{Call: _e.mock.On("GetAllDogus")}
}

func (_c *mockDoguGetter_GetAllDogus_Call) Run(run func()) *mockDoguGetter_GetAllDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDoguGetter_GetAllDogus_Call) Return(_a0 []string, _a1 error) *mockDoguGetter_GetAllDogus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguGetter_GetAllDogus_Call) RunAndReturn(run func() ([]string, error)) *mockDoguGetter_GetAllDogus_Call {
	_c.Call.Return(run)
	return _c
}

// GetDoguSpec provides a mock function with given fields: dogu
func (_m *mockDoguGetter) GetDoguSpec(dogu string) (core.Dogu, error) {
	ret := _m.Called(dogu)

	if len(ret) == 0 {
		panic("no return value specified for GetDoguSpec")
	}

	var r0 core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (core.Dogu, error)); ok {
		return rf(dogu)
	}
	if rf, ok := ret.Get(0).(func(string) core.Dogu); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Get(0).(core.Dogu)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dogu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguGetter_GetDoguSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoguSpec'
type mockDoguGetter_GetDoguSpec_Call struct {
	*mock.Call
}

// GetDoguSpec is a helper method to define mock.On call
//   - dogu string
func (_e *mockDoguGetter_Expecter) GetDoguSpec(dogu interface{}) *mockDoguGetter_GetDoguSpec_Call {
	return &mockDoguGetter_GetDoguSpec_Call{Call: _e.mock.On("GetDoguSpec", dogu)}
}

func (_c *mockDoguGetter_GetDoguSpec_Call) Run(run func(dogu string)) *mockDoguGetter_GetDoguSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguGetter_GetDoguSpec_Call) Return(_a0 core.Dogu, _a1 error) *mockDoguGetter_GetDoguSpec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguGetter_GetDoguSpec_Call) RunAndReturn(run func(string) (core.Dogu, error)) *mockDoguGetter_GetDoguSpec_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguGetter creates a new instance of mockDoguGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguGetter {
	mock := &mockDoguGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
