// Code generated by mockery v2.53.0. DO NOT EDIT.

package core

import mock "github.com/stretchr/testify/mock"

// MockFilterOption is an autogenerated mock type for the FilterOption type
type MockFilterOption struct {
	mock.Mock
}

type MockFilterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterOption) EXPECT() *MockFilterOption_Expecter {
	return &MockFilterOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: kvs
func (_m *MockFilterOption) Execute(kvs []KeyValue) []KeyValue {
	ret := _m.Called(kvs)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []KeyValue
	if rf, ok := ret.Get(0).(func([]KeyValue) []KeyValue); ok {
		r0 = rf(kvs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]KeyValue)
		}
	}

	return r0
}

// MockFilterOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilterOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - kvs []KeyValue
func (_e *MockFilterOption_Expecter) Execute(kvs interface{}) *MockFilterOption_Execute_Call {
	return &MockFilterOption_Execute_Call{Call: _e.mock.On("Execute", kvs)}
}

func (_c *MockFilterOption_Execute_Call) Run(run func(kvs []KeyValue)) *MockFilterOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]KeyValue))
	})
	return _c
}

func (_c *MockFilterOption_Execute_Call) Return(_a0 []KeyValue) *MockFilterOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilterOption_Execute_Call) RunAndReturn(run func([]KeyValue) []KeyValue) *MockFilterOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilterOption creates a new instance of MockFilterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterOption {
	mock := &MockFilterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
