// Code generated by mockery v2.53.0. DO NOT EDIT.

package core

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockWriteFileFunc is an autogenerated mock type for the WriteFileFunc type
type MockWriteFileFunc struct {
	mock.Mock
}

type MockWriteFileFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriteFileFunc) EXPECT() *MockWriteFileFunc_Expecter {
	return &MockWriteFileFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name, data, perm
func (_m *MockWriteFileFunc) Execute(name string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriteFileFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockWriteFileFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm fs.FileMode
func (_e *MockWriteFileFunc_Expecter) Execute(name interface{}, data interface{}, perm interface{}) *MockWriteFileFunc_Execute_Call {
	return &MockWriteFileFunc_Execute_Call{Call: _e.mock.On("Execute", name, data, perm)}
}

func (_c *MockWriteFileFunc_Execute_Call) Run(run func(name string, data []byte, perm fs.FileMode)) *MockWriteFileFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *MockWriteFileFunc_Execute_Call) Return(_a0 error) *MockWriteFileFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriteFileFunc_Execute_Call) RunAndReturn(run func(string, []byte, fs.FileMode) error) *MockWriteFileFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriteFileFunc creates a new instance of MockWriteFileFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriteFileFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriteFileFunc {
	mock := &MockWriteFileFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
