apiVersion: v1
values:
  images:
    cesControl: cloudogu/ces-exporter:2.0.0
patches:
  values.yaml:
    image:
      registry: "{{ registryFrom .images.cesControl }}"
      repository: "{{ repositoryFrom .images.cesControl }}"
      tag: "{{ tagFrom .images.cesControl }}"
