global:
  networkPolicies:
    enabled: true
  imagePullSecrets:
    - name: "ces-container-registries"
image:
  registry: docker.io
  repository: cloudogu/ces-exporter
  tag: 0.0.1-1743579305
imagePullPolicy: IfNotPresent
env:
  logLevel: info
  basePath: "/ces-exporter"
  exportCron: "*/2 * * * *"
apiKey:
  secretName: "ces-exporter-api"
  secretDataKey: "apiKey"
publicKey:
  configMapName: "ces-importer-public-key"
  configMapDataKey: "publicKey"
  data: ""
