global:
  networkPolicies:
    enabled: true
    gateway:
      matchLabels:
        k8s.cloudogu.com/component.name: k8s-ces-gateway
  imagePullSecrets:
    - name: "ces-container-registries"
image:
  registry: docker.io
  repository: cloudogu/ces-exporter
  tag: 2.0.0
imagePullPolicy: IfNotPresent
env:
  logLevel: info
  basePath: "/ces-exporter"
  #exportCron: "*/5 * * * *"
  #exportCronVerbose: true
apiKey:
  secretName: "ces-exporter-api"
  secretDataKey: "apiKey"
publicKey:
  configMapName: "ces-importer-public-key"
  configMapDataKey: "publicKey"
  data: ""
