#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

docker image load -i /tmp/exporter-image.tar
rm -f /tmp/exporter-image.tar
echo "================================================================================================================"
echo "===============================================================================================================!"
echo "================================================================================================================"

installed_version=$(dpkg-query -W -f='${Version}' ces-exporter)
echo "Installed version: $installed_version"

function etcdctl(){
  echo ""
}

API_KEY="$(etcdctl get config/ces-exporter/authentication/api_key)"

docker rm -f ces-exporter
docker run -e API_KEY="${API_KEY}" --name ces-exporter --restart=always -d "ces-exporter:${installed_version}"
