#!/bin/bash

# The postrm script should not fail, as this could lead to a non-deletable package. Disable all exit options.
set +o errexit
set +o nounset
set +o pipefail

docker rm -f ces-exporter
docker images "ces-exporter" --format "{{.Repository}}:{{.Tag}}" | xargs -r docker rmi -f
# Remove service of exporter
etcdctl rm services/exporter/registrator:exporter:8025


sudo ufw delete allow 7022 || echo "Failed to remove ufw rule to allow access to port 7022. If you do not use ufw, yo can ignore this error. Otherwise make sure to manually remove the firewall rule."
