// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	core "github.com/cloudogu/ces-exporter/core"

	mock "github.com/stretchr/testify/mock"
)

// GetGlobalConfigFunc is an autogenerated mock type for the GetGlobalConfigFunc type
type GetGlobalConfigFunc struct {
	mock.Mock
}

type GetGlobalConfigFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *GetGlobalConfigFunc) EXPECT() *GetGlobalConfigFunc_Expecter {
	return &GetGlobalConfigFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ignoreKeys
func (_m *GetGlobalConfigFunc) Execute(ignoreKeys []string) (core.GlobalConfig, error) {
	ret := _m.Called(ignoreKeys)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 core.GlobalConfig
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (core.GlobalConfig, error)); ok {
		return rf(ignoreKeys)
	}
	if rf, ok := ret.Get(0).(func([]string) core.GlobalConfig); ok {
		r0 = rf(ignoreKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GlobalConfig)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(ignoreKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalConfigFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetGlobalConfigFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ignoreKeys []string
func (_e *GetGlobalConfigFunc_Expecter) Execute(ignoreKeys interface{}) *GetGlobalConfigFunc_Execute_Call {
	return &GetGlobalConfigFunc_Execute_Call{Call: _e.mock.On("Execute", ignoreKeys)}
}

func (_c *GetGlobalConfigFunc_Execute_Call) Run(run func(ignoreKeys []string)) *GetGlobalConfigFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *GetGlobalConfigFunc_Execute_Call) Return(_a0 core.GlobalConfig, _a1 error) *GetGlobalConfigFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetGlobalConfigFunc_Execute_Call) RunAndReturn(run func([]string) (core.GlobalConfig, error)) *GetGlobalConfigFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetGlobalConfigFunc creates a new instance of GetGlobalConfigFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetGlobalConfigFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetGlobalConfigFunc {
	mock := &GetGlobalConfigFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
