// Code generated by mockery v2.53.0. DO NOT EDIT.

package maintenance

import (
	context "context"

	repository "github.com/cloudogu/k8s-registry-lib/repository"
	mock "github.com/stretchr/testify/mock"
)

// mockMaintenanceAdapter is an autogenerated mock type for the maintenanceAdapter type
type mockMaintenanceAdapter struct {
	mock.Mock
}

type mockMaintenanceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMaintenanceAdapter) EXPECT() *mockMaintenanceAdapter_Expecter {
	return &mockMaintenanceAdapter_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, content, force
func (_m *mockMaintenanceAdapter) Activate(ctx context.Context, content repository.MaintenanceModeDescription, force bool) error {
	ret := _m.Called(ctx, content, force)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.MaintenanceModeDescription, bool) error); ok {
		r0 = rf(ctx, content, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceAdapter_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type mockMaintenanceAdapter_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - content repository.MaintenanceModeDescription
//   - force bool
func (_e *mockMaintenanceAdapter_Expecter) Activate(ctx interface{}, content interface{}, force interface{}) *mockMaintenanceAdapter_Activate_Call {
	return &mockMaintenanceAdapter_Activate_Call{Call: _e.mock.On("Activate", ctx, content, force)}
}

func (_c *mockMaintenanceAdapter_Activate_Call) Run(run func(ctx context.Context, content repository.MaintenanceModeDescription, force bool)) *mockMaintenanceAdapter_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.MaintenanceModeDescription), args[2].(bool))
	})
	return _c
}

func (_c *mockMaintenanceAdapter_Activate_Call) Return(_a0 error) *mockMaintenanceAdapter_Activate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceAdapter_Activate_Call) RunAndReturn(run func(context.Context, repository.MaintenanceModeDescription, bool) error) *mockMaintenanceAdapter_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, force
func (_m *mockMaintenanceAdapter) Deactivate(ctx context.Context, force bool) error {
	ret := _m.Called(ctx, force)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockMaintenanceAdapter_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type mockMaintenanceAdapter_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - force bool
func (_e *mockMaintenanceAdapter_Expecter) Deactivate(ctx interface{}, force interface{}) *mockMaintenanceAdapter_Deactivate_Call {
	return &mockMaintenanceAdapter_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, force)}
}

func (_c *mockMaintenanceAdapter_Deactivate_Call) Run(run func(ctx context.Context, force bool)) *mockMaintenanceAdapter_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *mockMaintenanceAdapter_Deactivate_Call) Return(_a0 error) *mockMaintenanceAdapter_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockMaintenanceAdapter_Deactivate_Call) RunAndReturn(run func(context.Context, bool) error) *mockMaintenanceAdapter_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx
func (_m *mockMaintenanceAdapter) GetStatus(ctx context.Context) (repository.MaintenanceModeDescription, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 repository.MaintenanceModeDescription
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.MaintenanceModeDescription, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.MaintenanceModeDescription); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(repository.MaintenanceModeDescription)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// mockMaintenanceAdapter_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type mockMaintenanceAdapter_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockMaintenanceAdapter_Expecter) GetStatus(ctx interface{}) *mockMaintenanceAdapter_GetStatus_Call {
	return &mockMaintenanceAdapter_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *mockMaintenanceAdapter_GetStatus_Call) Run(run func(ctx context.Context)) *mockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockMaintenanceAdapter_GetStatus_Call) Return(_a0 repository.MaintenanceModeDescription, _a1 bool, _a2 error) *mockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *mockMaintenanceAdapter_GetStatus_Call) RunAndReturn(run func(context.Context) (repository.MaintenanceModeDescription, bool, error)) *mockMaintenanceAdapter_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockMaintenanceAdapter creates a new instance of mockMaintenanceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMaintenanceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMaintenanceAdapter {
	mock := &mockMaintenanceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
