// Code generated by mockery v2.53.0. DO NOT EDIT.

package maintenance

import (
	context "context"

	client "go.etcd.io/etcd/client/v2"

	mock "github.com/stretchr/testify/mock"
)

// MockKeysApi is an autogenerated mock type for the KeysApi type
type MockKeysApi struct {
	mock.Mock
}

type MockKeysApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeysApi) EXPECT() *MockKeysApi_Expecter {
	return &MockKeysApi_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, key, value
func (_m *MockKeysApi) Create(ctx context.Context, key string, value string) (*client.Response, error) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.Response, error)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.Response); ok {
		r0 = rf(ctx, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKeysApi_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockKeysApi_Expecter) Create(ctx interface{}, key interface{}, value interface{}) *MockKeysApi_Create_Call {
	return &MockKeysApi_Create_Call{Call: _e.mock.On("Create", ctx, key, value)}
}

func (_c *MockKeysApi_Create_Call) Run(run func(ctx context.Context, key string, value string)) *MockKeysApi_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKeysApi_Create_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_Create_Call) RunAndReturn(run func(context.Context, string, string) (*client.Response, error)) *MockKeysApi_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInOrder provides a mock function with given fields: ctx, dir, value, opts
func (_m *MockKeysApi) CreateInOrder(ctx context.Context, dir string, value string, opts *client.CreateInOrderOptions) (*client.Response, error) {
	ret := _m.Called(ctx, dir, value, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateInOrder")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.CreateInOrderOptions) (*client.Response, error)); ok {
		return rf(ctx, dir, value, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.CreateInOrderOptions) *client.Response); ok {
		r0 = rf(ctx, dir, value, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *client.CreateInOrderOptions) error); ok {
		r1 = rf(ctx, dir, value, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_CreateInOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInOrder'
type MockKeysApi_CreateInOrder_Call struct {
	*mock.Call
}

// CreateInOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - value string
//   - opts *client.CreateInOrderOptions
func (_e *MockKeysApi_Expecter) CreateInOrder(ctx interface{}, dir interface{}, value interface{}, opts interface{}) *MockKeysApi_CreateInOrder_Call {
	return &MockKeysApi_CreateInOrder_Call{Call: _e.mock.On("CreateInOrder", ctx, dir, value, opts)}
}

func (_c *MockKeysApi_CreateInOrder_Call) Run(run func(ctx context.Context, dir string, value string, opts *client.CreateInOrderOptions)) *MockKeysApi_CreateInOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*client.CreateInOrderOptions))
	})
	return _c
}

func (_c *MockKeysApi_CreateInOrder_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_CreateInOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_CreateInOrder_Call) RunAndReturn(run func(context.Context, string, string, *client.CreateInOrderOptions) (*client.Response, error)) *MockKeysApi_CreateInOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key, opts
func (_m *MockKeysApi) Delete(ctx context.Context, key string, opts *client.DeleteOptions) (*client.Response, error) {
	ret := _m.Called(ctx, key, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *client.DeleteOptions) (*client.Response, error)); ok {
		return rf(ctx, key, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *client.DeleteOptions) *client.Response); ok {
		r0 = rf(ctx, key, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *client.DeleteOptions) error); ok {
		r1 = rf(ctx, key, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeysApi_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts *client.DeleteOptions
func (_e *MockKeysApi_Expecter) Delete(ctx interface{}, key interface{}, opts interface{}) *MockKeysApi_Delete_Call {
	return &MockKeysApi_Delete_Call{Call: _e.mock.On("Delete", ctx, key, opts)}
}

func (_c *MockKeysApi_Delete_Call) Run(run func(ctx context.Context, key string, opts *client.DeleteOptions)) *MockKeysApi_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*client.DeleteOptions))
	})
	return _c
}

func (_c *MockKeysApi_Delete_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_Delete_Call) RunAndReturn(run func(context.Context, string, *client.DeleteOptions) (*client.Response, error)) *MockKeysApi_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key, opts
func (_m *MockKeysApi) Get(ctx context.Context, key string, opts *client.GetOptions) (*client.Response, error) {
	ret := _m.Called(ctx, key, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *client.GetOptions) (*client.Response, error)); ok {
		return rf(ctx, key, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *client.GetOptions) *client.Response); ok {
		r0 = rf(ctx, key, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *client.GetOptions) error); ok {
		r1 = rf(ctx, key, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKeysApi_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - opts *client.GetOptions
func (_e *MockKeysApi_Expecter) Get(ctx interface{}, key interface{}, opts interface{}) *MockKeysApi_Get_Call {
	return &MockKeysApi_Get_Call{Call: _e.mock.On("Get", ctx, key, opts)}
}

func (_c *MockKeysApi_Get_Call) Run(run func(ctx context.Context, key string, opts *client.GetOptions)) *MockKeysApi_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*client.GetOptions))
	})
	return _c
}

func (_c *MockKeysApi_Get_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_Get_Call) RunAndReturn(run func(context.Context, string, *client.GetOptions) (*client.Response, error)) *MockKeysApi_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, opts
func (_m *MockKeysApi) Set(ctx context.Context, key string, value string, opts *client.SetOptions) (*client.Response, error) {
	ret := _m.Called(ctx, key, value, opts)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.SetOptions) (*client.Response, error)); ok {
		return rf(ctx, key, value, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *client.SetOptions) *client.Response); ok {
		r0 = rf(ctx, key, value, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *client.SetOptions) error); ok {
		r1 = rf(ctx, key, value, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockKeysApi_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - opts *client.SetOptions
func (_e *MockKeysApi_Expecter) Set(ctx interface{}, key interface{}, value interface{}, opts interface{}) *MockKeysApi_Set_Call {
	return &MockKeysApi_Set_Call{Call: _e.mock.On("Set", ctx, key, value, opts)}
}

func (_c *MockKeysApi_Set_Call) Run(run func(ctx context.Context, key string, value string, opts *client.SetOptions)) *MockKeysApi_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*client.SetOptions))
	})
	return _c
}

func (_c *MockKeysApi_Set_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_Set_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_Set_Call) RunAndReturn(run func(context.Context, string, string, *client.SetOptions) (*client.Response, error)) *MockKeysApi_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, key, value
func (_m *MockKeysApi) Update(ctx context.Context, key string, value string) (*client.Response, error) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *client.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*client.Response, error)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *client.Response); ok {
		r0 = rf(ctx, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeysApi_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKeysApi_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockKeysApi_Expecter) Update(ctx interface{}, key interface{}, value interface{}) *MockKeysApi_Update_Call {
	return &MockKeysApi_Update_Call{Call: _e.mock.On("Update", ctx, key, value)}
}

func (_c *MockKeysApi_Update_Call) Run(run func(ctx context.Context, key string, value string)) *MockKeysApi_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKeysApi_Update_Call) Return(_a0 *client.Response, _a1 error) *MockKeysApi_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeysApi_Update_Call) RunAndReturn(run func(context.Context, string, string) (*client.Response, error)) *MockKeysApi_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Watcher provides a mock function with given fields: key, opts
func (_m *MockKeysApi) Watcher(key string, opts *client.WatcherOptions) client.Watcher {
	ret := _m.Called(key, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watcher")
	}

	var r0 client.Watcher
	if rf, ok := ret.Get(0).(func(string, *client.WatcherOptions) client.Watcher); ok {
		r0 = rf(key, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Watcher)
		}
	}

	return r0
}

// MockKeysApi_Watcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watcher'
type MockKeysApi_Watcher_Call struct {
	*mock.Call
}

// Watcher is a helper method to define mock.On call
//   - key string
//   - opts *client.WatcherOptions
func (_e *MockKeysApi_Expecter) Watcher(key interface{}, opts interface{}) *MockKeysApi_Watcher_Call {
	return &MockKeysApi_Watcher_Call{Call: _e.mock.On("Watcher", key, opts)}
}

func (_c *MockKeysApi_Watcher_Call) Run(run func(key string, opts *client.WatcherOptions)) *MockKeysApi_Watcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*client.WatcherOptions))
	})
	return _c
}

func (_c *MockKeysApi_Watcher_Call) Return(_a0 client.Watcher) *MockKeysApi_Watcher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeysApi_Watcher_Call) RunAndReturn(run func(string, *client.WatcherOptions) client.Watcher) *MockKeysApi_Watcher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeysApi creates a new instance of MockKeysApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeysApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeysApi {
	mock := &MockKeysApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
