// Code generated by mockery v2.53.0. DO NOT EDIT.

package maintenance

import (
	mock "github.com/stretchr/testify/mock"
	client "go.etcd.io/etcd/client/v2"
)

// mockEtcdGetter is an autogenerated mock type for the etcdGetter type
type mockEtcdGetter struct {
	mock.Mock
}

type mockEtcdGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEtcdGetter) EXPECT() *mockEtcdGetter_Expecter {
	return &mockEtcdGetter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockEtcdGetter) Delete(_a0 string, _a1 *client.DeleteOptions) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *client.DeleteOptions) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEtcdGetter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockEtcdGetter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 string
//   - _a1 *client.DeleteOptions
func (_e *mockEtcdGetter_Expecter) Delete(_a0 interface{}, _a1 interface{}) *mockEtcdGetter_Delete_Call {
	return &mockEtcdGetter_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1)}
}

func (_c *mockEtcdGetter_Delete_Call) Run(run func(_a0 string, _a1 *client.DeleteOptions)) *mockEtcdGetter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*client.DeleteOptions))
	})
	return _c
}

func (_c *mockEtcdGetter_Delete_Call) Return(_a0 error) *mockEtcdGetter_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEtcdGetter_Delete_Call) RunAndReturn(run func(string, *client.DeleteOptions) error) *mockEtcdGetter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *mockEtcdGetter) Get(_a0 string, _a1 *client.GetOptions) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *client.GetOptions) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *client.GetOptions) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, *client.GetOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEtcdGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockEtcdGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
//   - _a1 *client.GetOptions
func (_e *mockEtcdGetter_Expecter) Get(_a0 interface{}, _a1 interface{}) *mockEtcdGetter_Get_Call {
	return &mockEtcdGetter_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *mockEtcdGetter_Get_Call) Run(run func(_a0 string, _a1 *client.GetOptions)) *mockEtcdGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*client.GetOptions))
	})
	return _c
}

func (_c *mockEtcdGetter_Get_Call) Return(_a0 string, _a1 error) *mockEtcdGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEtcdGetter_Get_Call) RunAndReturn(run func(string, *client.GetOptions) (string, error)) *mockEtcdGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockEtcdGetter) Update(_a0 string, _a1 string, _a2 *client.SetOptions) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *client.SetOptions) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, *client.SetOptions) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, *client.SetOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEtcdGetter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockEtcdGetter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
//   - _a2 *client.SetOptions
func (_e *mockEtcdGetter_Expecter) Update(_a0 interface{}, _a1 interface{}, _a2 interface{}) *mockEtcdGetter_Update_Call {
	return &mockEtcdGetter_Update_Call{Call: _e.mock.On("Update", _a0, _a1, _a2)}
}

func (_c *mockEtcdGetter_Update_Call) Run(run func(_a0 string, _a1 string, _a2 *client.SetOptions)) *mockEtcdGetter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*client.SetOptions))
	})
	return _c
}

func (_c *mockEtcdGetter_Update_Call) Return(_a0 string, _a1 error) *mockEtcdGetter_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEtcdGetter_Update_Call) RunAndReturn(run func(string, string, *client.SetOptions) (string, error)) *mockEtcdGetter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEtcdGetter creates a new instance of mockEtcdGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEtcdGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEtcdGetter {
	mock := &mockEtcdGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
