// Code generated by mockery v2.53.0. DO NOT EDIT.

package maintenance

import mock "github.com/stretchr/testify/mock"

// mockEtcdConfigRepo is an autogenerated mock type for the etcdConfigRepo type
type mockEtcdConfigRepo struct {
	mock.Mock
}

type mockEtcdConfigRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEtcdConfigRepo) EXPECT() *mockEtcdConfigRepo_Expecter {
	return &mockEtcdConfigRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0
func (_m *mockEtcdConfigRepo) Delete(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEtcdConfigRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockEtcdConfigRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 string
func (_e *mockEtcdConfigRepo_Expecter) Delete(_a0 interface{}) *mockEtcdConfigRepo_Delete_Call {
	return &mockEtcdConfigRepo_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *mockEtcdConfigRepo_Delete_Call) Run(run func(_a0 string)) *mockEtcdConfigRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockEtcdConfigRepo_Delete_Call) Return(_a0 error) *mockEtcdConfigRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEtcdConfigRepo_Delete_Call) RunAndReturn(run func(string) error) *mockEtcdConfigRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *mockEtcdConfigRepo) Get(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEtcdConfigRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockEtcdConfigRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *mockEtcdConfigRepo_Expecter) Get(_a0 interface{}) *mockEtcdConfigRepo_Get_Call {
	return &mockEtcdConfigRepo_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *mockEtcdConfigRepo_Get_Call) Run(run func(_a0 string)) *mockEtcdConfigRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockEtcdConfigRepo_Get_Call) Return(_a0 string, _a1 error) *mockEtcdConfigRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEtcdConfigRepo_Get_Call) RunAndReturn(run func(string) (string, error)) *mockEtcdConfigRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: key, value
func (_m *mockEtcdConfigRepo) Update(key string, value string) (string, error) {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(key, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockEtcdConfigRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockEtcdConfigRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *mockEtcdConfigRepo_Expecter) Update(key interface{}, value interface{}) *mockEtcdConfigRepo_Update_Call {
	return &mockEtcdConfigRepo_Update_Call{Call: _e.mock.On("Update", key, value)}
}

func (_c *mockEtcdConfigRepo_Update_Call) Run(run func(key string, value string)) *mockEtcdConfigRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockEtcdConfigRepo_Update_Call) Return(_a0 string, _a1 error) *mockEtcdConfigRepo_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockEtcdConfigRepo_Update_Call) RunAndReturn(run func(string, string) (string, error)) *mockEtcdConfigRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEtcdConfigRepo creates a new instance of mockEtcdConfigRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEtcdConfigRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEtcdConfigRepo {
	mock := &mockEtcdConfigRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
