apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ces-exporter.name" . }}
  labels:
    {{- include "ces-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ces-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ces-exporter.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: exporter
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          volumeMounts:
            - mountPath: /etc/ces-exporter
              name: ces-exporter-server-certificate
              readOnly: false
          env:
            - name: LOG_LEVEL
              value: '{{ .Values.env.logLevel  | default "info" }}'
            - name: BASE_PATH
              value: '{{ .Values.env.basePath }}'
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.apiKey.secretDataKey }}
                  name: {{ .Values.apiKey.secretName }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: EXPORT_CRON
              value: '{{ .Values.env.exportCron}}'
            - name: EXPORT_CRON_VERBOSE
              value: '{{ .Values.env.exportCronVerbose}}'
          startupProbe:
            httpGet:
              path: "{{ .Values.env.basePath }}/health"
              port: 8080
          livenessProbe:
            httpGet:
              path: "{{ .Values.env.basePath }}/health"
              port: 8080
          readinessProbe:
            httpGet:
              path: "{{ .Values.env.basePath }}/health"
              port: 8080
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
      serviceAccountName: {{ include "ces-exporter.name" . }}
      volumes:
        # this secret is generated by ces-exporter during the start-up, the filenames will be those of the secret data map keys
        - name: ces-exporter-server-certificate
          secret:
            optional: true
            secretName: ces-exporter-server-certificate
