apiVersion: v1
kind: Service
metadata:
  name: {{ include "ces-exporter.name" . }}-dogu-exporter
  labels:
    {{- include "ces-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "7022"
      port: 7022
      targetPort: 22
  selector:
    dogu.name: "not_defined"