apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ces-exporter.name" . }}
  labels:
    {{- include "ces-exporter.labels" . | nindent 4 }}
spec:
  ingressClassName: k8s-ecosystem-ces-service
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "ces-exporter.name" . }}
                port:
                  number: 8080
            path: {{ .Values.env.basePath }}
            pathType: Prefix