apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.publicKey.configMapName }}
  labels:
    {{- include "ces-exporter.labels" . | nindent 4 }}
data:
  {{ .Values.publicKey.configMapDataKey }}: {{ .Values.publicKey.data }}