// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import mock "github.com/stretchr/testify/mock"

// mockGetAllDogusFunc is an autogenerated mock type for the getAllDogusFunc type
type mockGetAllDogusFunc struct {
	mock.Mock
}

type mockGetAllDogusFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGetAllDogusFunc) EXPECT() *mockGetAllDogusFunc_Expecter {
	return &mockGetAllDogusFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *mockGetAllDogusFunc) Execute() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGetAllDogusFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockGetAllDogusFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *mockGetAllDogusFunc_Expecter) Execute() *mockGetAllDogusFunc_Execute_Call {
	return &mockGetAllDogusFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *mockGetAllDogusFunc_Execute_Call) Run(run func()) *mockGetAllDogusFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockGetAllDogusFunc_Execute_Call) Return(_a0 []string, _a1 error) *mockGetAllDogusFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGetAllDogusFunc_Execute_Call) RunAndReturn(run func() ([]string, error)) *mockGetAllDogusFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGetAllDogusFunc creates a new instance of mockGetAllDogusFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetAllDogusFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetAllDogusFunc {
	mock := &mockGetAllDogusFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
