// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// getBackupSchedules provides a mock function with given fields: ctx
func (_m *MockProvider) getBackupSchedules(ctx context.Context) ([]backupSchedule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getBackupSchedules")
	}

	var r0 []backupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]backupSchedule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []backupSchedule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_getBackupSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getBackupSchedules'
type MockProvider_getBackupSchedules_Call struct {
	*mock.Call
}

// getBackupSchedules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) getBackupSchedules(ctx interface{}) *MockProvider_getBackupSchedules_Call {
	return &MockProvider_getBackupSchedules_Call{Call: _e.mock.On("getBackupSchedules", ctx)}
}

func (_c *MockProvider_getBackupSchedules_Call) Run(run func(ctx context.Context)) *MockProvider_getBackupSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_getBackupSchedules_Call) Return(_a0 []backupSchedule, _a1 error) *MockProvider_getBackupSchedules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_getBackupSchedules_Call) RunAndReturn(run func(context.Context) ([]backupSchedule, error)) *MockProvider_getBackupSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// getDoguConfigs provides a mock function with given fields: ctx
func (_m *MockProvider) getDoguConfigs(ctx context.Context) ([]doguConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getDoguConfigs")
	}

	var r0 []doguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]doguConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []doguConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]doguConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_getDoguConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDoguConfigs'
type MockProvider_getDoguConfigs_Call struct {
	*mock.Call
}

// getDoguConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) getDoguConfigs(ctx interface{}) *MockProvider_getDoguConfigs_Call {
	return &MockProvider_getDoguConfigs_Call{Call: _e.mock.On("getDoguConfigs", ctx)}
}

func (_c *MockProvider_getDoguConfigs_Call) Run(run func(ctx context.Context)) *MockProvider_getDoguConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_getDoguConfigs_Call) Return(_a0 []doguConfig, _a1 error) *MockProvider_getDoguConfigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_getDoguConfigs_Call) RunAndReturn(run func(context.Context) ([]doguConfig, error)) *MockProvider_getDoguConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// getGlobalConfigs provides a mock function with given fields: ctx
func (_m *MockProvider) getGlobalConfigs(ctx context.Context) ([]keyValue, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getGlobalConfigs")
	}

	var r0 []keyValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]keyValue, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []keyValue); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keyValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_getGlobalConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getGlobalConfigs'
type MockProvider_getGlobalConfigs_Call struct {
	*mock.Call
}

// getGlobalConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) getGlobalConfigs(ctx interface{}) *MockProvider_getGlobalConfigs_Call {
	return &MockProvider_getGlobalConfigs_Call{Call: _e.mock.On("getGlobalConfigs", ctx)}
}

func (_c *MockProvider_getGlobalConfigs_Call) Run(run func(ctx context.Context)) *MockProvider_getGlobalConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_getGlobalConfigs_Call) Return(_a0 []keyValue, _a1 error) *MockProvider_getGlobalConfigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_getGlobalConfigs_Call) RunAndReturn(run func(context.Context) ([]keyValue, error)) *MockProvider_getGlobalConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
