// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	core "github.com/cloudogu/ces-exporter/core"
	mock "github.com/stretchr/testify/mock"
)

// mockGetConfigFunc is an autogenerated mock type for the getConfigFunc type
type mockGetConfigFunc struct {
	mock.Mock
}

type mockGetConfigFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGetConfigFunc) EXPECT() *mockGetConfigFunc_Expecter {
	return &mockGetConfigFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dogu, ignoreKeys
func (_m *mockGetConfigFunc) Execute(dogu string, ignoreKeys []string) (core.DoguConfig, error) {
	ret := _m.Called(dogu, ignoreKeys)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 core.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (core.DoguConfig, error)); ok {
		return rf(dogu, ignoreKeys)
	}
	if rf, ok := ret.Get(0).(func(string, []string) core.DoguConfig); ok {
		r0 = rf(dogu, ignoreKeys)
	} else {
		r0 = ret.Get(0).(core.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(dogu, ignoreKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGetConfigFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockGetConfigFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dogu string
//   - ignoreKeys []string
func (_e *mockGetConfigFunc_Expecter) Execute(dogu interface{}, ignoreKeys interface{}) *mockGetConfigFunc_Execute_Call {
	return &mockGetConfigFunc_Execute_Call{Call: _e.mock.On("Execute", dogu, ignoreKeys)}
}

func (_c *mockGetConfigFunc_Execute_Call) Run(run func(dogu string, ignoreKeys []string)) *mockGetConfigFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *mockGetConfigFunc_Execute_Call) Return(_a0 core.DoguConfig, _a1 error) *mockGetConfigFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGetConfigFunc_Execute_Call) RunAndReturn(run func(string, []string) (core.DoguConfig, error)) *mockGetConfigFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGetConfigFunc creates a new instance of mockGetConfigFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetConfigFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetConfigFunc {
	mock := &mockGetConfigFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
