// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	core "github.com/cloudogu/ces-exporter/core"
	mock "github.com/stretchr/testify/mock"
)

// mockGetNormalConfigFunc is an autogenerated mock type for the getNormalConfigFunc type
type mockGetNormalConfigFunc struct {
	mock.Mock
}

type mockGetNormalConfigFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGetNormalConfigFunc) EXPECT() *mockGetNormalConfigFunc_Expecter {
	return &mockGetNormalConfigFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dogu, ignoreKeys
func (_m *mockGetNormalConfigFunc) Execute(dogu string, ignoreKeys []string) ([]core.KeyValue, error) {
	ret := _m.Called(dogu, ignoreKeys)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []core.KeyValue
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) ([]core.KeyValue, error)); ok {
		return rf(dogu, ignoreKeys)
	}
	if rf, ok := ret.Get(0).(func(string, []string) []core.KeyValue); ok {
		r0 = rf(dogu, ignoreKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.KeyValue)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(dogu, ignoreKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGetNormalConfigFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockGetNormalConfigFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dogu string
//   - ignoreKeys []string
func (_e *mockGetNormalConfigFunc_Expecter) Execute(dogu interface{}, ignoreKeys interface{}) *mockGetNormalConfigFunc_Execute_Call {
	return &mockGetNormalConfigFunc_Execute_Call{Call: _e.mock.On("Execute", dogu, ignoreKeys)}
}

func (_c *mockGetNormalConfigFunc_Execute_Call) Run(run func(dogu string, ignoreKeys []string)) *mockGetNormalConfigFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *mockGetNormalConfigFunc_Execute_Call) Return(_a0 []core.KeyValue, _a1 error) *mockGetNormalConfigFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGetNormalConfigFunc_Execute_Call) RunAndReturn(run func(string, []string) ([]core.KeyValue, error)) *mockGetNormalConfigFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGetNormalConfigFunc creates a new instance of mockGetNormalConfigFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetNormalConfigFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetNormalConfigFunc {
	mock := &mockGetNormalConfigFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
