// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigurationProvider is an autogenerated mock type for the ConfigurationProvider type
type MockConfigurationProvider struct {
	mock.Mock
}

type MockConfigurationProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurationProvider) EXPECT() *MockConfigurationProvider_Expecter {
	return &MockConfigurationProvider_Expecter{mock: &_m.Mock}
}

// getBackupSchedules provides a mock function with given fields: ctx
func (_m *MockConfigurationProvider) getBackupSchedules(ctx context.Context) ([]backupSchedule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getBackupSchedules")
	}

	var r0 []backupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]backupSchedule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []backupSchedule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationProvider_getBackupSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getBackupSchedules'
type MockConfigurationProvider_getBackupSchedules_Call struct {
	*mock.Call
}

// getBackupSchedules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurationProvider_Expecter) getBackupSchedules(ctx interface{}) *MockConfigurationProvider_getBackupSchedules_Call {
	return &MockConfigurationProvider_getBackupSchedules_Call{Call: _e.mock.On("getBackupSchedules", ctx)}
}

func (_c *MockConfigurationProvider_getBackupSchedules_Call) Run(run func(ctx context.Context)) *MockConfigurationProvider_getBackupSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigurationProvider_getBackupSchedules_Call) Return(_a0 []backupSchedule, _a1 error) *MockConfigurationProvider_getBackupSchedules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationProvider_getBackupSchedules_Call) RunAndReturn(run func(context.Context) ([]backupSchedule, error)) *MockConfigurationProvider_getBackupSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// getDoguConfigs provides a mock function with given fields: ctx
func (_m *MockConfigurationProvider) getDoguConfigs(ctx context.Context) ([]doguConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getDoguConfigs")
	}

	var r0 []doguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]doguConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []doguConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]doguConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationProvider_getDoguConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDoguConfigs'
type MockConfigurationProvider_getDoguConfigs_Call struct {
	*mock.Call
}

// getDoguConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurationProvider_Expecter) getDoguConfigs(ctx interface{}) *MockConfigurationProvider_getDoguConfigs_Call {
	return &MockConfigurationProvider_getDoguConfigs_Call{Call: _e.mock.On("getDoguConfigs", ctx)}
}

func (_c *MockConfigurationProvider_getDoguConfigs_Call) Run(run func(ctx context.Context)) *MockConfigurationProvider_getDoguConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigurationProvider_getDoguConfigs_Call) Return(_a0 []doguConfig, _a1 error) *MockConfigurationProvider_getDoguConfigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationProvider_getDoguConfigs_Call) RunAndReturn(run func(context.Context) ([]doguConfig, error)) *MockConfigurationProvider_getDoguConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// getGlobalConfigs provides a mock function with given fields: ctx
func (_m *MockConfigurationProvider) getGlobalConfigs(ctx context.Context) ([]keyValue, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getGlobalConfigs")
	}

	var r0 []keyValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]keyValue, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []keyValue); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]keyValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigurationProvider_getGlobalConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getGlobalConfigs'
type MockConfigurationProvider_getGlobalConfigs_Call struct {
	*mock.Call
}

// getGlobalConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurationProvider_Expecter) getGlobalConfigs(ctx interface{}) *MockConfigurationProvider_getGlobalConfigs_Call {
	return &MockConfigurationProvider_getGlobalConfigs_Call{Call: _e.mock.On("getGlobalConfigs", ctx)}
}

func (_c *MockConfigurationProvider_getGlobalConfigs_Call) Run(run func(ctx context.Context)) *MockConfigurationProvider_getGlobalConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigurationProvider_getGlobalConfigs_Call) Return(_a0 []keyValue, _a1 error) *MockConfigurationProvider_getGlobalConfigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigurationProvider_getGlobalConfigs_Call) RunAndReturn(run func(context.Context) ([]keyValue, error)) *MockConfigurationProvider_getGlobalConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigurationProvider creates a new instance of MockConfigurationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurationProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurationProvider {
	mock := &MockConfigurationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
