// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguVersionRegistry is an autogenerated mock type for the doguVersionRegistry type
type mockDoguVersionRegistry struct {
	mock.Mock
}

type mockDoguVersionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguVersionRegistry) EXPECT() *mockDoguVersionRegistry_Expecter {
	return &mockDoguVersionRegistry_Expecter{mock: &_m.Mock}
}

// GetCurrentOfAll provides a mock function with given fields: ctx
func (_m *mockDoguVersionRegistry) GetCurrentOfAll(ctx context.Context) ([]dogu.SimpleNameVersion, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentOfAll")
	}

	var r0 []dogu.SimpleNameVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dogu.SimpleNameVersion, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dogu.SimpleNameVersion); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dogu.SimpleNameVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguVersionRegistry_GetCurrentOfAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentOfAll'
type mockDoguVersionRegistry_GetCurrentOfAll_Call struct {
	*mock.Call
}

// GetCurrentOfAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockDoguVersionRegistry_Expecter) GetCurrentOfAll(ctx interface{}) *mockDoguVersionRegistry_GetCurrentOfAll_Call {
	return &mockDoguVersionRegistry_GetCurrentOfAll_Call{Call: _e.mock.On("GetCurrentOfAll", ctx)}
}

func (_c *mockDoguVersionRegistry_GetCurrentOfAll_Call) Run(run func(ctx context.Context)) *mockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockDoguVersionRegistry_GetCurrentOfAll_Call) Return(_a0 []dogu.SimpleNameVersion, _a1 error) *mockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguVersionRegistry_GetCurrentOfAll_Call) RunAndReturn(run func(context.Context) ([]dogu.SimpleNameVersion, error)) *mockDoguVersionRegistry_GetCurrentOfAll_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguVersionRegistry creates a new instance of mockDoguVersionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguVersionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguVersionRegistry {
	mock := &mockDoguVersionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
