// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import mock "github.com/stretchr/testify/mock"

// MockConfigurationProvider is an autogenerated mock type for the ConfigurationProvider type
type MockConfigurationProvider struct {
	mock.Mock
}

type MockConfigurationProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurationProvider) EXPECT() *MockConfigurationProvider_Expecter {
	return &MockConfigurationProvider_Expecter{mock: &_m.Mock}
}

// NewMockConfigurationProvider creates a new instance of MockConfigurationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurationProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurationProvider {
	mock := &MockConfigurationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
