// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	config "github.com/cloudogu/k8s-registry-lib/config"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguConfigRepository is an autogenerated mock type for the doguConfigRepository type
type mockDoguConfigRepository struct {
	mock.Mock
}

type mockDoguConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigRepository) EXPECT() *mockDoguConfigRepository_Expecter {
	return &mockDoguConfigRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name
func (_m *mockDoguConfigRepository) Get(ctx context.Context, name dogu.SimpleName) (config.DoguConfig, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) (config.DoguConfig, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) config.DoguConfig); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(config.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dogu.SimpleName) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockDoguConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name dogu.SimpleName
func (_e *mockDoguConfigRepository_Expecter) Get(ctx interface{}, name interface{}) *mockDoguConfigRepository_Get_Call {
	return &mockDoguConfigRepository_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *mockDoguConfigRepository_Get_Call) Run(run func(ctx context.Context, name dogu.SimpleName)) *mockDoguConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleName))
	})
	return _c
}

func (_c *mockDoguConfigRepository_Get_Call) Return(_a0 config.DoguConfig, _a1 error) *mockDoguConfigRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepository_Get_Call) RunAndReturn(run func(context.Context, dogu.SimpleName) (config.DoguConfig, error)) *mockDoguConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguConfigRepository creates a new instance of mockDoguConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguConfigRepository {
	mock := &mockDoguConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
