// Code generated by mockery v2.53.0. DO NOT EDIT.

package configuration

import (
	context "context"

	v1 "github.com/cloudogu/k8s-backup-operator/pkg/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockBackupScheduleRuntimeClient is an autogenerated mock type for the backupScheduleRuntimeClient type
type mockBackupScheduleRuntimeClient struct {
	mock.Mock
}

type mockBackupScheduleRuntimeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupScheduleRuntimeClient) EXPECT() *mockBackupScheduleRuntimeClient_Expecter {
	return &mockBackupScheduleRuntimeClient_Expecter{mock: &_m.Mock}
}

// ListBackupSchedules provides a mock function with given fields: ctx
func (_m *mockBackupScheduleRuntimeClient) ListBackupSchedules(ctx context.Context) (*v1.BackupScheduleList, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupSchedules")
	}

	var r0 *v1.BackupScheduleList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1.BackupScheduleList, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1.BackupScheduleList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupScheduleList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleRuntimeClient_ListBackupSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBackupSchedules'
type mockBackupScheduleRuntimeClient_ListBackupSchedules_Call struct {
	*mock.Call
}

// ListBackupSchedules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockBackupScheduleRuntimeClient_Expecter) ListBackupSchedules(ctx interface{}) *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call {
	return &mockBackupScheduleRuntimeClient_ListBackupSchedules_Call{Call: _e.mock.On("ListBackupSchedules", ctx)}
}

func (_c *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call) Run(run func(ctx context.Context)) *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call) Return(_a0 *v1.BackupScheduleList, _a1 error) *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call) RunAndReturn(run func(context.Context) (*v1.BackupScheduleList, error)) *mockBackupScheduleRuntimeClient_ListBackupSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackupScheduleRuntimeClient creates a new instance of mockBackupScheduleRuntimeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackupScheduleRuntimeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackupScheduleRuntimeClient {
	mock := &mockBackupScheduleRuntimeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
